// African Names - 100 male, 100 female, 100 last names
public abstract class KdspAfricanNames {

    public static func GetMaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Kwame"; }
        if i == 1 { return "Kofi"; }
        if i == 2 { return "Chidi"; }
        if i == 3 { return "Emeka"; }
        if i == 4 { return "Olumide"; }
        if i == 5 { return "Babatunde"; }
        if i == 6 { return "Sekou"; }
        if i == 7 { return "Mandla"; }
        if i == 8 { return "Thabo"; }
        if i == 9 { return "Sipho"; }
        if i == 10 { return "Amadi"; }
        if i == 11 { return "Obinna"; }
        if i == 12 { return "Oluwaseun"; }
        if i == 13 { return "Adebayo"; }
        if i == 14 { return "Chinua"; }
        if i == 15 { return "Kwaku"; }
        if i == 16 { return "Yaw"; }
        if i == 17 { return "Kojo"; }
        if i == 18 { return "Abayomi"; }
        if i == 19 { return "Adekunle"; }
        if i == 20 { return "Bamidele"; }
        if i == 21 { return "Chibueze"; }
        if i == 22 { return "Danjuma"; }
        if i == 23 { return "Ekene"; }
        if i == 24 { return "Femi"; }
        if i == 25 { return "Gbenga"; }
        if i == 26 { return "Hakeem"; }
        if i == 27 { return "Ikenna"; }
        if i == 28 { return "Jelani"; }
        if i == 29 { return "Kamau"; }
        if i == 30 { return "Lekan"; }
        if i == 31 { return "Musa"; }
        if i == 32 { return "Nnamdi"; }
        if i == 33 { return "Obafemi"; }
        if i == 34 { return "Paki"; }
        if i == 35 { return "Rashidi"; }
        if i == 36 { return "Segun"; }
        if i == 37 { return "Taiwo"; }
        if i == 38 { return "Uche"; }
        if i == 39 { return "Vusi"; }
        if i == 40 { return "Wole"; }
        if i == 41 { return "Yemi"; }
        if i == 42 { return "Zuberi"; }
        if i == 43 { return "Abiodun"; }
        if i == 44 { return "Bongani"; }
        if i == 45 { return "Chinedu"; }
        if i == 46 { return "Dumisani"; }
        if i == 47 { return "Ebuka"; }
        if i == 48 { return "Folarin"; }
        if i == 49 { return "Godwin"; }
        if i == 50 { return "Hassan"; }
        if i == 51 { return "Ifeanyi"; }
        if i == 52 { return "Jomo"; }
        if i == 53 { return "Kelechi"; }
        if i == 54 { return "Lwazi"; }
        if i == 55 { return "Mawuli"; }
        if i == 56 { return "Nkosana"; }
        if i == 57 { return "Okonkwo"; }
        if i == 58 { return "Precious"; }
        if i == 59 { return "Rafiki"; }
        if i == 60 { return "Sanusi"; }
        if i == 61 { return "Tendai"; }
        if i == 62 { return "Uzoma"; }
        if i == 63 { return "Victor"; }
        if i == 64 { return "Wasiu"; }
        if i == 65 { return "Xolani"; }
        if i == 66 { return "Yinka"; }
        if i == 67 { return "Zola"; }
        if i == 68 { return "Adisa"; }
        if i == 69 { return "Bosede"; }
        if i == 70 { return "Chiamaka"; }
        if i == 71 { return "Dele"; }
        if i == 72 { return "Emmanuel"; }
        if i == 73 { return "Faraji"; }
        if i == 74 { return "Gift"; }
        if i == 75 { return "Hector"; }
        if i == 76 { return "Ife"; }
        if i == 77 { return "Justice"; }
        if i == 78 { return "Kayode"; }
        if i == 79 { return "Lucky"; }
        if i == 80 { return "Melusi"; }
        if i == 81 { return "Njoku"; }
        if i == 82 { return "Ojo"; }
        if i == 83 { return "Promise"; }
        if i == 84 { return "Quami"; }
        if i == 85 { return "Rotimi"; }
        if i == 86 { return "Simba"; }
        if i == 87 { return "Tobi"; }
        if i == 88 { return "Unity"; }
        if i == 89 { return "Vincent"; }
        if i == 90 { return "Wisdom"; }
        if i == 91 { return "Xolile"; }
        if i == 92 { return "Yusuf"; }
        if i == 93 { return "Zephania"; }
        if i == 94 { return "Akintola"; }
        if i == 95 { return "Bankole"; }
        if i == 96 { return "Chukwuma"; }
        if i == 97 { return "Dubem"; }
        if i == 98 { return "Ezenwa"; }
        if i == 99 { return "Festus"; }
        if i == 100 { return "Kwasi"; }
        if i == 101 { return "Bakari"; }
        if i == 102 { return "Chike"; }
        if i == 103 { return "Ekon"; }
        if i == 104 { return "Gyasi"; }
        if i == 105 { return "Hasani"; }
        if i == 106 { return "Idris"; }
        if i == 107 { return "Jabari"; }
        if i == 108 { return "Obi"; }
        if i == 109 { return "Rudo"; }
        if i == 110 { return "Sefu"; }
        if i == 111 { return "Wekesa"; }
        if i == 112 { return "Abioye"; }
        if i == 113 { return "Babajide"; }
        if i == 114 { return "Diallo"; }
        if i == 115 { return "Folami"; }
        if i == 116 { return "Gowon"; }
        if i == 117 { return "Hondo"; }
        if i == 118 { return "Lumumba"; }
        if i == 119 { return "Mosi"; }
        if i == 120 { return "Nuru"; }
        if i == 121 { return "Tafari"; }
        if i == 122 { return "Umaru"; }
        if i == 123 { return "Yohannes"; }
        if i == 124 { return "Zik"; }
        if i == 125 { return "Bandele"; }
        if i == 126 { return "Dakarai"; }
        if i == 127 { return "Enitan"; }
        if i == 128 { return "Kagiso"; }
        if i == 129 { return "Tumelo"; }
        if i == 130 { return "Katlego"; }
        if i == 131 { return "Neo"; }
        if i == 132 { return "Lesego"; }
        if i == 133 { return "Tshepo"; }
        if i == 134 { return "Karabo"; }
        if i == 135 { return "Sizwe"; }
        if i == 136 { return "Themba"; }
        if i == 137 { return "Ayanda"; }
        if i == 138 { return "Bhekizizwe"; }
        if i == 139 { return "Dingane"; }
        if i == 140 { return "Fanyana"; }
        if i == 141 { return "Gatsha"; }
        if i == 142 { return "Jabulani"; }
        if i == 143 { return "Khulekani"; }
        if i == 144 { return "Mduduzi"; }
        if i == 145 { return "Nhlanhla"; }
        if i == 146 { return "Phumlani"; }
        if i == 147 { return "Sandile"; }
        if i == 148 { return "Thulani"; }
        if i == 149 { return "Velaphi"; }
        return "Kwame";
    }

    public static func GetFemaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Amara"; }
        if i == 1 { return "Zuri"; }
        if i == 2 { return "Nia"; }
        if i == 3 { return "Aisha"; }
        if i == 4 { return "Fatou"; }
        if i == 5 { return "Adaeze"; }
        if i == 6 { return "Chiamaka"; }
        if i == 7 { return "Oluchi"; }
        if i == 8 { return "Ngozi"; }
        if i == 9 { return "Thandiwe"; }
        if i == 10 { return "Ama"; }
        if i == 11 { return "Akosua"; }
        if i == 12 { return "Yaa"; }
        if i == 13 { return "Abena"; }
        if i == 14 { return "Efua"; }
        if i == 15 { return "Adjoa"; }
        if i == 16 { return "Adwoa"; }
        if i == 17 { return "Afia"; }
        if i == 18 { return "Afua"; }
        if i == 19 { return "Akua"; }
        if i == 20 { return "Adanna"; }
        if i == 21 { return "Binta"; }
        if i == 22 { return "Chidinma"; }
        if i == 23 { return "Damilola"; }
        if i == 24 { return "Ebele"; }
        if i == 25 { return "Folake"; }
        if i == 26 { return "Gbemisola"; }
        if i == 27 { return "Hauwa"; }
        if i == 28 { return "Ife"; }
        if i == 29 { return "Jumoke"; }
        if i == 30 { return "Kemi"; }
        if i == 31 { return "Lindiwe"; }
        if i == 32 { return "Makena"; }
        if i == 33 { return "Nneka"; }
        if i == 34 { return "Ogechi"; }
        if i == 35 { return "Precious"; }
        if i == 36 { return "Queen"; }
        if i == 37 { return "Ronke"; }
        if i == 38 { return "Sade"; }
        if i == 39 { return "Titi"; }
        if i == 40 { return "Uchenna"; }
        if i == 41 { return "Victoria"; }
        if i == 42 { return "Wambui"; }
        if i == 43 { return "Yetunde"; }
        if i == 44 { return "Zainab"; }
        if i == 45 { return "Abimbola"; }
        if i == 46 { return "Blessing"; }
        if i == 47 { return "Chinelo"; }
        if i == 48 { return "Doyin"; }
        if i == 49 { return "Ekanem"; }
        if i == 50 { return "Fatima"; }
        if i == 51 { return "Gladys"; }
        if i == 52 { return "Halima"; }
        if i == 53 { return "Ifeoma"; }
        if i == 54 { return "Joy"; }
        if i == 55 { return "Kefilwe"; }
        if i == 56 { return "Lola"; }
        if i == 57 { return "Mariam"; }
        if i == 58 { return "Nomvula"; }
        if i == 59 { return "Omolara"; }
        if i == 60 { return "Patience"; }
        if i == 61 { return "Rashida"; }
        if i == 62 { return "Simisola"; }
        if i == 63 { return "Tolu"; }
        if i == 64 { return "Unoma"; }
        if i == 65 { return "Vivian"; }
        if i == 66 { return "Wuraola"; }
        if i == 67 { return "Yemi"; }
        if i == 68 { return "Zikhona"; }
        if i == 69 { return "Ada"; }
        if i == 70 { return "Busola"; }
        if i == 71 { return "Chika"; }
        if i == 72 { return "Dunni"; }
        if i == 73 { return "Enitan"; }
        if i == 74 { return "Funke"; }
        if i == 75 { return "Grace"; }
        if i == 76 { return "Helen"; }
        if i == 77 { return "Ifunanya"; }
        if i == 78 { return "Janet"; }
        if i == 79 { return "Kehinde"; }
        if i == 80 { return "Lilian"; }
        if i == 81 { return "Mary"; }
        if i == 82 { return "Njideka"; }
        if i == 83 { return "Olaide"; }
        if i == 84 { return "Peace"; }
        if i == 85 { return "Ruth"; }
        if i == 86 { return "Sarah"; }
        if i == 87 { return "Taiwo"; }
        if i == 88 { return "Uzochi"; }
        if i == 89 { return "Vera"; }
        if i == 90 { return "Wande"; }
        if i == 91 { return "Yinka"; }
        if i == 92 { return "Zanele"; }
        if i == 93 { return "Adaora"; }
        if i == 94 { return "Bukola"; }
        if i == 95 { return "Comfort"; }
        if i == 96 { return "Dupe"; }
        if i == 97 { return "Esther"; }
        if i == 98 { return "Favor"; }
        if i == 99 { return "Gift"; }
        if i == 100 { return "Dalila"; }
        if i == 101 { return "Folasade"; }
        if i == 102 { return "Jendayi"; }
        if i == 103 { return "Kessie"; }
        if i == 104 { return "Nailah"; }
        if i == 105 { return "Panya"; }
        if i == 106 { return "Ramla"; }
        if i == 107 { return "Saada"; }
        if i == 108 { return "Thema"; }
        if i == 109 { return "Uzuri"; }
        if i == 110 { return "Wangari"; }
        if i == 111 { return "Zalika"; }
        if i == 112 { return "Bosede"; }
        if i == 113 { return "Chinwe"; }
        if i == 114 { return "Ekene"; }
        if i == 115 { return "Fumilayo"; }
        if i == 116 { return "Gugu"; }
        if i == 117 { return "Hadiza"; }
        if i == 118 { return "Ijeoma"; }
        if i == 119 { return "Kagiso"; }
        if i == 120 { return "Lerato"; }
        if i == 121 { return "Mbali"; }
        if i == 122 { return "Onyeka"; }
        if i == 123 { return "Palesa"; }
        if i == 124 { return "Rufaro"; }
        if i == 125 { return "Sibongile"; }
        if i == 126 { return "Urenna"; }
        if i == 127 { return "Wanjiru"; }
        if i == 128 { return "Yejide"; }
        if i == 129 { return "Bunmi"; }
        if i == 130 { return "Desta"; }
        if i == 131 { return "Ntombi"; }
        if i == 132 { return "Refilwe"; }
        if i == 133 { return "Boitumelo"; }
        if i == 134 { return "Dikeledi"; }
        if i == 135 { return "Lesedi"; }
        if i == 136 { return "Mmabatho"; }
        if i == 137 { return "Naledi"; }
        if i == 138 { return "Palesa-Rose"; }
        if i == 139 { return "Reabetswe"; }
        if i == 140 { return "Tebogo"; }
        if i == 141 { return "Tshegofatso"; }
        if i == 142 { return "Zodwa"; }
        if i == 143 { return "Andile"; }
        if i == 144 { return "Buhle"; }
        if i == 145 { return "Duduzile"; }
        if i == 146 { return "Fikile"; }
        if i == 147 { return "Gugulethu"; }
        if i == 148 { return "Hlengiwe"; }
        if i == 149 { return "Khanyisile"; }
        return "Amara";
    }

    public static func GetLastName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 147);
        if i == 0 { return "Okonkwo"; }
        if i == 1 { return "Mensah"; }
        if i == 2 { return "Adeyemi"; }
        if i == 3 { return "Nkosi"; }
        if i == 4 { return "Diallo"; }
        if i == 5 { return "Mbeki"; }
        if i == 6 { return "Asante"; }
        if i == 7 { return "Kamara"; }
        if i == 8 { return "Okafor"; }
        if i == 9 { return "Mwangi"; }
        if i == 10 { return "Abubakar"; }
        if i == 11 { return "Bello"; }
        if i == 12 { return "Chukwu"; }
        if i == 13 { return "Dlamini"; }
        if i == 14 { return "Eze"; }
        if i == 15 { return "Fofana"; }
        if i == 16 { return "Gueye"; }
        if i == 17 { return "Hassan"; }
        if i == 18 { return "Ibrahim"; }
        if i == 19 { return "Jallow"; }
        if i == 20 { return "Kone"; }
        if i == 21 { return "Lumumba"; }
        if i == 22 { return "Moyo"; }
        if i == 23 { return "Ndlovu"; }
        if i == 24 { return "Okoro"; }
        if i == 25 { return "Phiri"; }
        if i == 26 { return "Qwabe"; }
        if i == 27 { return "Radebe"; }
        if i == 28 { return "Sesay"; }
        if i == 29 { return "Toure"; }
        if i == 30 { return "Udo"; }
        if i == 31 { return "Venter"; }
        if i == 32 { return "Wanjiku"; }
        if i == 33 { return "Xulu"; }
        if i == 34 { return "Yeboah"; }
        if i == 35 { return "Zuma"; }
        if i == 36 { return "Adebisi"; }
        if i == 37 { return "Banda"; }
        if i == 38 { return "Conteh"; }
        if i == 39 { return "Dube"; }
        if i == 40 { return "Ekwueme"; }
        if i == 41 { return "Fadipe"; }
        if i == 42 { return "Gowon"; }
        if i == 43 { return "Hlophe"; }
        if i == 44 { return "Ige"; }
        if i == 45 { return "Jabari"; }
        if i == 46 { return "Kalu"; }
        if i == 47 { return "Langa"; }
        if i == 48 { return "Mabaso"; }
        if i == 49 { return "Njoku"; }
        if i == 50 { return "Onyeka"; }
        if i == 51 { return "Padmore"; }
        if i == 52 { return "Quaye"; }
        if i == 53 { return "Ramaphosa"; }
        if i == 54 { return "Sibanda"; }
        if i == 55 { return "Traore"; }
        if i == 56 { return "Ugwu"; }
        if i == 57 { return "Vilakazi"; }
        if i == 58 { return "Williams"; }
        if i == 59 { return "Xhosa"; }
        if i == 60 { return "Yakubu"; }
        if i == 61 { return "Zulu"; }
        if i == 62 { return "Akintunde"; }
        if i == 63 { return "Boateng"; }
        if i == 64 { return "Cele"; }
        if i == 65 { return "Diouf"; }
        if i == 66 { return "Emecheta"; }
        if i == 67 { return "Fashola"; }
        if i == 68 { return "Gcaba"; }
        if i == 69 { return "Haidara"; }
        if i == 70 { return "Ihejirika"; }
        if i == 71 { return "Johnson"; }
        if i == 72 { return "Kenyatta"; }
        if i == 73 { return "Ladipo"; }
        if i == 74 { return "Mandela"; }
        if i == 75 { return "Nkrumah"; }
        if i == 76 { return "Odinga"; }
        if i == 77 { return "Patel"; }
        if i == 78 { return "Qoboza"; }
        if i == 79 { return "Ruto"; }
        if i == 80 { return "Soyinka"; }
        if i == 81 { return "Tambo"; }
        if i == 82 { return "Uzoka"; }
        if i == 83 { return "Vorster"; }
        if i == 84 { return "Weah"; }
        if i == 85 { return "Xaba"; }
        if i == 86 { return "Yusuf"; }
        if i == 87 { return "Zewde"; }
        if i == 88 { return "Achebe"; }
        if i == 89 { return "Bokassa"; }
        if i == 90 { return "Compaoré"; }
        if i == 91 { return "Diop"; }
        if i == 92 { return "Essien"; }
        if i == 93 { return "Faye"; }
        if i == 94 { return "Gbagbo"; }
        if i == 95 { return "Houphouet"; }
        if i == 96 { return "Irele"; }
        if i == 97 { return "Jagne"; }
        if i == 98 { return "Keita"; }
        if i == 99 { return "Lekota"; }
        if i == 100 { return "Abara"; }
        if i == 101 { return "Bankole"; }
        if i == 102 { return "Folarin"; }
        if i == 103 { return "Gbeho"; }
        if i == 104 { return "Hakizimana"; }
        if i == 105 { return "Igwe"; }
        if i == 106 { return "Jalloh"; }
        if i == 107 { return "Lumu"; }
        if i == 108 { return "Ndiaye"; }
        if i == 109 { return "Obasanjo"; }
        if i == 110 { return "Preira"; }
        if i == 111 { return "Rugambwa"; }
        if i == 112 { return "Sankara"; }
        if i == 113 { return "Uwimana"; }
        if i == 114 { return "Wanjala"; }
        if i == 115 { return "Zongo"; }
        if i == 116 { return "Chirwa"; }
        if i == 117 { return "Danjuma"; }
        if i == 118 { return "Elumelu"; }
        if i == 119 { return "Hussein"; }
        if i == 120 { return "Juma"; }
        if i == 121 { return "Kagame"; }
        if i == 122 { return "Lubega"; }
        if i == 123 { return "Musa"; }
        if i == 124 { return "Umar"; }
        if i == 125 { return "Waweru"; }
        if i == 126 { return "Cisse"; }
        if i == 127 { return "Mthembu"; }
        if i == 128 { return "Nkomo"; }
        if i == 129 { return "Khumalo"; }
        if i == 130 { return "Buthelezi"; }
        if i == 131 { return "Gumede"; }
        if i == 132 { return "Hadebe"; }
        if i == 133 { return "Jiyane"; }
        if i == 134 { return "Khoza"; }
        if i == 135 { return "Luthuli"; }
        if i == 136 { return "Mahlangu"; }
        if i == 137 { return "Ngcobo"; }
        if i == 138 { return "Ntuli"; }
        if i == 139 { return "Pilane"; }
        if i == 140 { return "Sithole"; }
        if i == 141 { return "Tshabalala"; }
        if i == 142 { return "Zwane"; }
        if i == 143 { return "Mokoena"; }
        if i == 144 { return "Molefe"; }
        if i == 145 { return "Sekhukhune"; }
        if i == 146 { return "Thwala"; }
        return "Okonkwo";
    }
}
