// Chinese Names - 100 male, 100 female, 100 last names
public abstract class KdspChineseNames {

    public static func GetMaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Wei"; }
        if i == 1 { return "Chen"; }
        if i == 2 { return "Jun"; }
        if i == 3 { return "Ming"; }
        if i == 4 { return "Fang"; }
        if i == 5 { return "Jian"; }
        if i == 6 { return "Lei"; }
        if i == 7 { return "Tao"; }
        if i == 8 { return "Long"; }
        if i == 9 { return "Feng"; }
        if i == 10 { return "Hao"; }
        if i == 11 { return "Bo"; }
        if i == 12 { return "Cheng"; }
        if i == 13 { return "Dong"; }
        if i == 14 { return "Guo"; }
        if i == 15 { return "Hong"; }
        if i == 16 { return "Jin"; }
        if i == 17 { return "Kai"; }
        if i == 18 { return "Liang"; }
        if i == 19 { return "Ning"; }
        if i == 20 { return "Peng"; }
        if i == 21 { return "Qiang"; }
        if i == 22 { return "Rui"; }
        if i == 23 { return "Shan"; }
        if i == 24 { return "Tian"; }
        if i == 25 { return "Xiang"; }
        if i == 26 { return "Yang"; }
        if i == 27 { return "Zhen"; }
        if i == 28 { return "Zhong"; }
        if i == 29 { return "Bao"; }
        if i == 30 { return "Cai"; }
        if i == 31 { return "Da"; }
        if i == 32 { return "En"; }
        if i == 33 { return "Fu"; }
        if i == 34 { return "Gang"; }
        if i == 35 { return "Hai"; }
        if i == 36 { return "Jie"; }
        if i == 37 { return "Kun"; }
        if i == 38 { return "Lin"; }
        if i == 39 { return "Mao"; }
        if i == 40 { return "Nan"; }
        if i == 41 { return "Ping"; }
        if i == 42 { return "Qing"; }
        if i == 43 { return "Song"; }
        if i == 44 { return "Tu"; }
        if i == 45 { return "Wen"; }
        if i == 46 { return "Xi"; }
        if i == 47 { return "Yi"; }
        if i == 48 { return "Zhao"; }
        if i == 49 { return "Zhi"; }
        if i == 50 { return "An"; }
        if i == 51 { return "Bing"; }
        if i == 52 { return "Chang"; }
        if i == 53 { return "Deng"; }
        if i == 54 { return "Fei"; }
        if i == 55 { return "Guang"; }
        if i == 56 { return "He"; }
        if i == 57 { return "Jing"; }
        if i == 58 { return "Kang"; }
        if i == 59 { return "Li"; }
        if i == 60 { return "Man"; }
        if i == 61 { return "Ou"; }
        if i == 62 { return "Pu"; }
        if i == 63 { return "Quan"; }
        if i == 64 { return "Ren"; }
        if i == 65 { return "Sheng"; }
        if i == 66 { return "Tang"; }
        if i == 67 { return "Wang"; }
        if i == 68 { return "Xin"; }
        if i == 69 { return "Yu"; }
        if i == 70 { return "Ze"; }
        if i == 71 { return "Ai"; }
        if i == 72 { return "Bin"; }
        if i == 73 { return "Chu"; }
        if i == 74 { return "Di"; }
        if i == 75 { return "Fan"; }
        if i == 76 { return "Ge"; }
        if i == 77 { return "Heng"; }
        if i == 78 { return "Ji"; }
        if i == 79 { return "Ke"; }
        if i == 80 { return "Lu"; }
        if i == 81 { return "Mo"; }
        if i == 82 { return "Po"; }
        if i == 83 { return "Qi"; }
        if i == 84 { return "Ru"; }
        if i == 85 { return "Shen"; }
        if i == 86 { return "Ting"; }
        if i == 87 { return "Wu"; }
        if i == 88 { return "Xu"; }
        if i == 89 { return "Yan"; }
        if i == 90 { return "Zhe"; }
        if i == 91 { return "Bai"; }
        if i == 92 { return "Can"; }
        if i == 93 { return "Dian"; }
        if i == 94 { return "Er"; }
        if i == 95 { return "Gan"; }
        if i == 96 { return "Hua"; }
        if i == 97 { return "Jiu"; }
        if i == 98 { return "Kong"; }
        if i == 99 { return "Lei"; }
        if i == 100 { return "Rong"; }
        if i == 101 { return "Yong"; }
        if i == 102 { return "Chao"; }
        if i == 103 { return "De"; }
        if i == 104 { return "Meng"; }
        if i == 105 { return "Cong"; }
        if i == 106 { return "Fa"; }
        if i == 107 { return "Zhirong"; }
        if i == 108 { return "Weimin"; }
        if i == 109 { return "Jianguo"; }
        if i == 110 { return "Xiaolong"; }
        if i == 111 { return "Tengfei"; }
        if i == 112 { return "Yuhang"; }
        if i == 113 { return "Zichen"; }
        if i == 114 { return "Haoran"; }
        if i == 115 { return "Junjie"; }
        if i == 116 { return "Mingze"; }
        if i == 117 { return "Yichen"; }
        if i == 118 { return "Ruoxi"; }
        if i == 119 { return "Zihao"; }
        if i == 120 { return "Chengxi"; }
        if i == 121 { return "Boyang"; }
        if i == 122 { return "Tianyu"; }
        if i == 123 { return "Shaoqing"; }
        if i == 124 { return "Xuefeng"; }
        if i == 125 { return "Guanting"; }
        if i == 126 { return "Zhiyuan"; }
        if i == 127 { return "Wenbo"; }
        if i == 128 { return "Jingyu"; }
        if i == 129 { return "Haodong"; }
        if i == 130 { return "Yanlin"; }
        if i == 131 { return "Qixuan"; }
        if i == 132 { return "Shixin"; }
        if i == 133 { return "Lianjie"; }
        if i == 134 { return "Dongmei"; }
        if i == 135 { return "Zhengyang"; }
        if i == 136 { return "Kaiwen"; }
        if i == 137 { return "Xingchen"; }
        if i == 138 { return "Renshu"; }
        if i == 139 { return "Yifan"; }
        if i == 140 { return "Zeyu"; }
        if i == 141 { return "Chuanli"; }
        if i == 142 { return "Bingwen"; }
        if i == 143 { return "Tingfeng"; }
        if i == 144 { return "Xiaojian"; }
        if i == 145 { return "Guozhi"; }
        if i == 146 { return "Zhenhua"; }
        if i == 147 { return "Weisheng"; }
        if i == 148 { return "Jinhai"; }
        if i == 149 { return "Honghui"; }
        return "Wei";
    }

    public static func GetFemaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Mei"; }
        if i == 1 { return "Ling"; }
        if i == 2 { return "Xiu"; }
        if i == 3 { return "Yan"; }
        if i == 4 { return "Hui"; }
        if i == 5 { return "Li"; }
        if i == 6 { return "Fang"; }
        if i == 7 { return "Jing"; }
        if i == 8 { return "Xia"; }
        if i == 9 { return "Yun"; }
        if i == 10 { return "Hua"; }
        if i == 11 { return "Qian"; }
        if i == 12 { return "Juan"; }
        if i == 13 { return "Lan"; }
        if i == 14 { return "Ping"; }
        if i == 15 { return "Hong"; }
        if i == 16 { return "Ying"; }
        if i == 17 { return "Xue"; }
        if i == 18 { return "Zhi"; }
        if i == 19 { return "Wei"; }
        if i == 20 { return "Rui"; }
        if i == 21 { return "Min"; }
        if i == 22 { return "Na"; }
        if i == 23 { return "Yu"; }
        if i == 24 { return "Qin"; }
        if i == 25 { return "Chun"; }
        if i == 26 { return "Dan"; }
        if i == 27 { return "Feng"; }
        if i == 28 { return "Gui"; }
        if i == 29 { return "Huan"; }
        if i == 30 { return "Jiao"; }
        if i == 31 { return "Kun"; }
        if i == 32 { return "Lian"; }
        if i == 33 { return "Ning"; }
        if i == 34 { return "Pei"; }
        if i == 35 { return "Qing"; }
        if i == 36 { return "Shu"; }
        if i == 37 { return "Ting"; }
        if i == 38 { return "Wan"; }
        if i == 39 { return "Xin"; }
        if i == 40 { return "Yi"; }
        if i == 41 { return "Zhen"; }
        if i == 42 { return "Ai"; }
        if i == 43 { return "Bi"; }
        if i == 44 { return "Cui"; }
        if i == 45 { return "Die"; }
        if i == 46 { return "En"; }
        if i == 47 { return "Fei"; }
        if i == 48 { return "Ge"; }
        if i == 49 { return "He"; }
        if i == 50 { return "Ji"; }
        if i == 51 { return "Ke"; }
        if i == 52 { return "Lu"; }
        if i == 53 { return "Meng"; }
        if i == 54 { return "Ni"; }
        if i == 55 { return "Ou"; }
        if i == 56 { return "Pu"; }
        if i == 57 { return "Qi"; }
        if i == 58 { return "Ran"; }
        if i == 59 { return "Si"; }
        if i == 60 { return "Tian"; }
        if i == 61 { return "Wu"; }
        if i == 62 { return "Xi"; }
        if i == 63 { return "Ya"; }
        if i == 64 { return "Zhu"; }
        if i == 65 { return "An"; }
        if i == 66 { return "Bo"; }
        if i == 67 { return "Chang"; }
        if i == 68 { return "Du"; }
        if i == 69 { return "Er"; }
        if i == 70 { return "Fan"; }
        if i == 71 { return "Guo"; }
        if i == 72 { return "Hai"; }
        if i == 73 { return "Jin"; }
        if i == 74 { return "Kai"; }
        if i == 75 { return "Lei"; }
        if i == 76 { return "Man"; }
        if i == 77 { return "Nuo"; }
        if i == 78 { return "Pan"; }
        if i == 79 { return "Qiong"; }
        if i == 80 { return "Rong"; }
        if i == 81 { return "Shan"; }
        if i == 82 { return "Tao"; }
        if i == 83 { return "Wen"; }
        if i == 84 { return "Xiao"; }
        if i == 85 { return "Yao"; }
        if i == 86 { return "Zi"; }
        if i == 87 { return "Bao"; }
        if i == 88 { return "Chen"; }
        if i == 89 { return "Dong"; }
        if i == 90 { return "Fu"; }
        if i == 91 { return "Gang"; }
        if i == 92 { return "Heng"; }
        if i == 93 { return "Jian"; }
        if i == 94 { return "Kang"; }
        if i == 95 { return "Lin"; }
        if i == 96 { return "Mo"; }
        if i == 97 { return "Nan"; }
        if i == 98 { return "Song"; }
        if i == 99 { return "Yuan"; }
        if i == 100 { return "E"; }
        if i == 101 { return "Jia"; }
        if i == 102 { return "Rou"; }
        if i == 103 { return "Ah"; }
        if i == 104 { return "Ju"; }
        if i == 105 { return "Su"; }
        if i == 106 { return "Zhao"; }
        if i == 107 { return "Xiaowei"; }
        if i == 108 { return "Yating"; }
        if i == 109 { return "Zhenzhen"; }
        if i == 110 { return "Meiling"; }
        if i == 111 { return "Qiuyue"; }
        if i == 112 { return "Xinyi"; }
        if i == 113 { return "Ruolan"; }
        if i == 114 { return "Jingyi"; }
        if i == 115 { return "Haiyan"; }
        if i == 116 { return "Yumeng"; }
        if i == 117 { return "Zixin"; }
        if i == 118 { return "Chunhua"; }
        if i == 119 { return "Baozhen"; }
        if i == 120 { return "Tingting"; }
        if i == 121 { return "Shufen"; }
        if i == 122 { return "Xuelian"; }
        if i == 123 { return "Guiying"; }
        if i == 124 { return "Zhilan"; }
        if i == 125 { return "Wenxin"; }
        if i == 126 { return "Jiaxin"; }
        if i == 127 { return "Huifang"; }
        if i == 128 { return "Yanmei"; }
        if i == 129 { return "Qianqian"; }
        if i == 130 { return "Shurong"; }
        if i == 131 { return "Lihua"; }
        if i == 132 { return "Dongxue"; }
        if i == 133 { return "Zhiruo"; }
        if i == 134 { return "Kexin"; }
        if i == 135 { return "Xingyu"; }
        if i == 136 { return "Renxiang"; }
        if i == 137 { return "Yiran"; }
        if i == 138 { return "Zelin"; }
        if i == 139 { return "Chunyan"; }
        if i == 140 { return "Binglan"; }
        if i == 141 { return "Tianxin"; }
        if i == 142 { return "Xiaohong"; }
        if i == 143 { return "Guifen"; }
        if i == 144 { return "Zhenni"; }
        if i == 145 { return "Weiwei"; }
        if i == 146 { return "Jinfeng"; }
        if i == 147 { return "Hongxia"; }
        if i == 148 { return "Yaling"; }
        if i == 149 { return "Quanxiu"; }
        return "Mei";
    }

    public static func GetLastName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Wang"; }
        if i == 1 { return "Li"; }
        if i == 2 { return "Zhang"; }
        if i == 3 { return "Liu"; }
        if i == 4 { return "Chen"; }
        if i == 5 { return "Yang"; }
        if i == 6 { return "Huang"; }
        if i == 7 { return "Zhao"; }
        if i == 8 { return "Wu"; }
        if i == 9 { return "Zhou"; }
        if i == 10 { return "Xu"; }
        if i == 11 { return "Sun"; }
        if i == 12 { return "Ma"; }
        if i == 13 { return "Zhu"; }
        if i == 14 { return "Hu"; }
        if i == 15 { return "Guo"; }
        if i == 16 { return "He"; }
        if i == 17 { return "Lin"; }
        if i == 18 { return "Gao"; }
        if i == 19 { return "Luo"; }
        if i == 20 { return "Zheng"; }
        if i == 21 { return "Liang"; }
        if i == 22 { return "Xie"; }
        if i == 23 { return "Song"; }
        if i == 24 { return "Tang"; }
        if i == 25 { return "Xu"; }
        if i == 26 { return "Han"; }
        if i == 27 { return "Feng"; }
        if i == 28 { return "Deng"; }
        if i == 29 { return "Cao"; }
        if i == 30 { return "Peng"; }
        if i == 31 { return "Zeng"; }
        if i == 32 { return "Xiao"; }
        if i == 33 { return "Tian"; }
        if i == 34 { return "Dong"; }
        if i == 35 { return "Pan"; }
        if i == 36 { return "Yuan"; }
        if i == 37 { return "Cai"; }
        if i == 38 { return "Jiang"; }
        if i == 39 { return "Yu"; }
        if i == 40 { return "Du"; }
        if i == 41 { return "Ye"; }
        if i == 42 { return "Cheng"; }
        if i == 43 { return "Wei"; }
        if i == 44 { return "Su"; }
        if i == 45 { return "Lu"; }
        if i == 46 { return "Ding"; }
        if i == 47 { return "Ren"; }
        if i == 48 { return "Shen"; }
        if i == 49 { return "Yao"; }
        if i == 50 { return "Cui"; }
        if i == 51 { return "Zhong"; }
        if i == 52 { return "Fan"; }
        if i == 53 { return "Fang"; }
        if i == 54 { return "Wang"; }
        if i == 55 { return "Shi"; }
        if i == 56 { return "Liao"; }
        if i == 57 { return "Jin"; }
        if i == 58 { return "Qin"; }
        if i == 59 { return "Jia"; }
        if i == 60 { return "Xiong"; }
        if i == 61 { return "Meng"; }
        if i == 62 { return "Qiu"; }
        if i == 63 { return "Bai"; }
        if i == 64 { return "Hou"; }
        if i == 65 { return "Yin"; }
        if i == 66 { return "Chang"; }
        if i == 67 { return "Long"; }
        if i == 68 { return "Wan"; }
        if i == 69 { return "Duan"; }
        if i == 70 { return "Lei"; }
        if i == 71 { return "Hao"; }
        if i == 72 { return "Kong"; }
        if i == 73 { return "Shao"; }
        if i == 74 { return "Shi"; }
        if i == 75 { return "Mao"; }
        if i == 76 { return "Qian"; }
        if i == 77 { return "Dai"; }
        if i == 78 { return "Mo"; }
        if i == 79 { return "Tan"; }
        if i == 80 { return "Wen"; }
        if i == 81 { return "Zhuang"; }
        if i == 82 { return "Yan"; }
        if i == 83 { return "Ke"; }
        if i == 84 { return "Gu"; }
        if i == 85 { return "Sheng"; }
        if i == 86 { return "Qiao"; }
        if i == 87 { return "Lai"; }
        if i == 88 { return "Geng"; }
        if i == 89 { return "Xia"; }
        if i == 90 { return "Niu"; }
        if i == 91 { return "Ji"; }
        if i == 92 { return "An"; }
        if i == 93 { return "Lan"; }
        if i == 94 { return "Fu"; }
        if i == 95 { return "Kang"; }
        if i == 96 { return "Mu"; }
        if i == 97 { return "Tong"; }
        if i == 98 { return "Hua"; }
        if i == 99 { return "Bi"; }
        if i == 100 { return "Chu"; }
        if i == 101 { return "You"; }
        if i == 102 { return "Tao"; }
        if i == 103 { return "Qi"; }
        if i == 104 { return "Zou"; }
        if i == 105 { return "Shui"; }
        if i == 106 { return "Dou"; }
        if i == 107 { return "Yun"; }
        if i == 108 { return "Ge"; }
        if i == 109 { return "Xi"; }
        if i == 110 { return "Lang"; }
        if i == 111 { return "Miao"; }
        if i == 112 { return "Bao"; }
        if i == 113 { return "Ouyang"; }
        if i == 114 { return "Shangguan"; }
        if i == 115 { return "Situ"; }
        if i == 116 { return "Zhuge"; }
        if i == 117 { return "Xiahou"; }
        if i == 118 { return "Huangfu"; }
        if i == 119 { return "Gongsun"; }
        if i == 120 { return "Murong"; }
        if i == 121 { return "Duanmu"; }
        if i == 122 { return "Baili"; }
        if i == 123 { return "Dongfang"; }
        if i == 124 { return "Ximen"; }
        if i == 125 { return "Nangong"; }
        if i == 126 { return "Puyang"; }
        if i == 127 { return "Zhongli"; }
        if i == 128 { return "Yuchi"; }
        if i == 129 { return "Changsun"; }
        if i == 130 { return "Sikong"; }
        if i == 131 { return "Shentu"; }
        if i == 132 { return "Helian"; }
        if i == 133 { return "Yuwen"; }
        if i == 134 { return "Tuoba"; }
        if i == 135 { return "Wanyan"; }
        if i == 136 { return "Yelu"; }
        if i == 137 { return "Xianyu"; }
        if i == 138 { return "Zhangsun"; }
        if i == 139 { return "Chunyu"; }
        if i == 140 { return "Taishi"; }
        if i == 141 { return "Gongye"; }
        if i == 142 { return "Leng"; }
        if i == 143 { return "Nie"; }
        if i == 144 { return "Kuang"; }
        if i == 145 { return "Lou"; }
        if i == 146 { return "Mi"; }
        if i == 147 { return "Ben"; }
        if i == 148 { return "Ju"; }
        if i == 149 { return "Che"; }
        return "Wang";
    }
}
