// European Names - 100 male, 100 female, 100 last names
public abstract class KdspEuropeanNames {

    public static func GetMaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Hans"; }
        if i == 1 { return "Klaus"; }
        if i == 2 { return "Dieter"; }
        if i == 3 { return "Wolfgang"; }
        if i == 4 { return "Jurgen"; }
        if i == 5 { return "Heinrich"; }
        if i == 6 { return "Friedrich"; }
        if i == 7 { return "Wilhelm"; }
        if i == 8 { return "Ludwig"; }
        if i == 9 { return "Karl"; }
        if i == 10 { return "Francois"; }
        if i == 11 { return "Pierre"; }
        if i == 12 { return "Jean"; }
        if i == 13 { return "Michel"; }
        if i == 14 { return "Claude"; }
        if i == 15 { return "Jacques"; }
        if i == 16 { return "Philippe"; }
        if i == 17 { return "Alain"; }
        if i == 18 { return "Bernard"; }
        if i == 19 { return "Laurent"; }
        if i == 20 { return "Giovanni"; }
        if i == 21 { return "Marco"; }
        if i == 22 { return "Luca"; }
        if i == 23 { return "Giuseppe"; }
        if i == 24 { return "Alessandro"; }
        if i == 25 { return "Francesco"; }
        if i == 26 { return "Matteo"; }
        if i == 27 { return "Andrea"; }
        if i == 28 { return "Lorenzo"; }
        if i == 29 { return "Stefano"; }
        if i == 30 { return "Matias"; }
        if i == 31 { return "Joao"; }
        if i == 32 { return "Pedro"; }
        if i == 33 { return "Carlos"; }
        if i == 34 { return "Miguel"; }
        if i == 35 { return "Fernando"; }
        if i == 36 { return "Rui"; }
        if i == 37 { return "Nuno"; }
        if i == 38 { return "Tiago"; }
        if i == 39 { return "Andre"; }
        if i == 40 { return "Lars"; }
        if i == 41 { return "Erik"; }
        if i == 42 { return "Anders"; }
        if i == 43 { return "Olaf"; }
        if i == 44 { return "Magnus"; }
        if i == 45 { return "Sven"; }
        if i == 46 { return "Bjorn"; }
        if i == 47 { return "Niklas"; }
        if i == 48 { return "Gustaf"; }
        if i == 49 { return "Henrik"; }
        if i == 50 { return "Pieter"; }
        if i == 51 { return "Willem"; }
        if i == 52 { return "Dirk"; }
        if i == 53 { return "Joost"; }
        if i == 54 { return "Maarten"; }
        if i == 55 { return "Jeroen"; }
        if i == 56 { return "Bas"; }
        if i == 57 { return "Ruud"; }
        if i == 58 { return "Koen"; }
        if i == 59 { return "Wouter"; }
        if i == 60 { return "Alexandros"; }
        if i == 61 { return "Dimitrios"; }
        if i == 62 { return "Georgios"; }
        if i == 63 { return "Konstantinos"; }
        if i == 64 { return "Nikolaos"; }
        if i == 65 { return "Christos"; }
        if i == 66 { return "Ioannis"; }
        if i == 67 { return "Panagiotis"; }
        if i == 68 { return "Vasilis"; }
        if i == 69 { return "Stavros"; }
        if i == 70 { return "Rainer"; }
        if i == 71 { return "Florian"; }
        if i == 72 { return "Markus"; }
        if i == 73 { return "Stefan"; }
        if i == 74 { return "Thomas"; }
        if i == 75 { return "Christian"; }
        if i == 76 { return "Andreas"; }
        if i == 77 { return "Martin"; }
        if i == 78 { return "Michael"; }
        if i == 79 { return "Sebastian"; }
        if i == 80 { return "Olivier"; }
        if i == 81 { return "Thierry"; }
        if i == 82 { return "Yves"; }
        if i == 83 { return "Antoine"; }
        if i == 84 { return "Nicolas"; }
        if i == 85 { return "Julien"; }
        if i == 86 { return "Maxime"; }
        if i == 87 { return "Hugo"; }
        if i == 88 { return "Louis"; }
        if i == 89 { return "Leo"; }
        if i == 90 { return "Antonio"; }
        if i == 91 { return "Roberto"; }
        if i == 92 { return "Fabio"; }
        if i == 93 { return "Sergio"; }
        if i == 94 { return "Paolo"; }
        if i == 95 { return "Mario"; }
        if i == 96 { return "Enrico"; }
        if i == 97 { return "Daniele"; }
        if i == 98 { return "Riccardo"; }
        if i == 99 { return "Nicola"; }
        if i == 100 { return "Bastien"; }
        if i == 101 { return "Cormac"; }
        if i == 102 { return "Emil"; }
        if i == 103 { return "Fabien"; }
        if i == 104 { return "Gunnar"; }
        if i == 105 { return "Ivo"; }
        if i == 106 { return "Jasper"; }
        if i == 107 { return "Matthias"; }
        if i == 108 { return "Nils"; }
        if i == 109 { return "Otto"; }
        if i == 110 { return "Pascal"; }
        if i == 111 { return "Quentin"; }
        if i == 112 { return "Rafael"; }
        if i == 113 { return "Tobias"; }
        if i == 114 { return "Ulrich"; }
        if i == 115 { return "Viggo"; }
        if i == 116 { return "Xavier"; }
        if i == 117 { return "Yannick"; }
        if i == 118 { return "Zoltan"; }
        if i == 119 { return "Bruno"; }
        if i == 120 { return "Cesare"; }
        if i == 121 { return "Dominik"; }
        if i == 122 { return "Enzo"; }
        if i == 123 { return "Giancarlo"; }
        if i == 124 { return "Ivan"; }
        if i == 125 { return "Joachim"; }
        if i == 126 { return "Konstantin"; }
        if i == 127 { return "Marcel"; }
        if i == 128 { return "Piero"; }
        if i == 129 { return "Rasmus"; }
        if i == 130 { return "Umberto"; }
        if i == 131 { return "Valentin"; }
        if i == 132 { return "Werner"; }
        if i == 133 { return "Aldo"; }
        if i == 134 { return "Sixten"; }
        if i == 135 { return "Torbjorn"; }
        if i == 136 { return "Vittorio"; }
        if i == 137 { return "Waldemar"; }
        if i == 138 { return "Ambrogio"; }
        if i == 139 { return "Benedikt"; }
        if i == 140 { return "Corentin"; }
        if i == 141 { return "Donatello"; }
        if i == 142 { return "Eusebio"; }
        if i == 143 { return "Ferdinand"; }
        if i == 144 { return "Gottfried"; }
        if i == 145 { return "Hjalmar"; }
        if i == 146 { return "Isidoro"; }
        if i == 147 { return "Jean-Luc"; }
        if i == 148 { return "Kristoffer"; }
        if i == 149 { return "Leopold"; }
        return "Hans";
    }

    public static func GetFemaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 147);
        if i == 0 { return "Ingrid"; }
        if i == 1 { return "Helga"; }
        if i == 2 { return "Greta"; }
        if i == 3 { return "Heidi"; }
        if i == 4 { return "Monika"; }
        if i == 5 { return "Ursula"; }
        if i == 6 { return "Brigitte"; }
        if i == 7 { return "Sabine"; }
        if i == 8 { return "Petra"; }
        if i == 9 { return "Claudia"; }
        if i == 10 { return "Marie"; }
        if i == 11 { return "Sophie"; }
        if i == 12 { return "Camille"; }
        if i == 13 { return "Charlotte"; }
        if i == 14 { return "Isabelle"; }
        if i == 15 { return "Nathalie"; }
        if i == 16 { return "Aurelie"; }
        if i == 17 { return "Sylvie"; }
        if i == 18 { return "Martine"; }
        if i == 19 { return "Monique"; }
        if i == 20 { return "Francesca"; }
        if i == 21 { return "Giulia"; }
        if i == 22 { return "Chiara"; }
        if i == 23 { return "Sara"; }
        if i == 24 { return "Valentina"; }
        if i == 25 { return "Alessia"; }
        if i == 26 { return "Martina"; }
        if i == 27 { return "Federica"; }
        if i == 28 { return "Elisa"; }
        if i == 29 { return "Silvia"; }
        if i == 30 { return "Ana"; }
        if i == 31 { return "Maria"; }
        if i == 32 { return "Joana"; }
        if i == 33 { return "Ines"; }
        if i == 34 { return "Catarina"; }
        if i == 35 { return "Margarida"; }
        if i == 36 { return "Beatriz"; }
        if i == 37 { return "Leonor"; }
        if i == 38 { return "Carolina"; }
        if i == 39 { return "Rita"; }
        if i == 40 { return "Astrid"; }
        if i == 41 { return "Sigrid"; }
        if i == 42 { return "Ingeborg"; }
        if i == 43 { return "Karin"; }
        if i == 44 { return "Annika"; }
        if i == 45 { return "Lena"; }
        if i == 46 { return "Maja"; }
        if i == 47 { return "Elin"; }
        if i == 48 { return "Frida"; }
        if i == 49 { return "Linnea"; }
        if i == 50 { return "Elke"; }
        if i == 51 { return "Annemarie"; }
        if i == 52 { return "Liesbeth"; }
        if i == 53 { return "Marieke"; }
        if i == 54 { return "Sanne"; }
        if i == 55 { return "Femke"; }
        if i == 56 { return "Lotte"; }
        if i == 57 { return "Emma"; }
        if i == 58 { return "Fleur"; }
        if i == 59 { return "Eva"; }
        if i == 60 { return "Eleni"; }
        if i == 61 { return "Dimitra"; }
        if i == 62 { return "Georgia"; }
        if i == 63 { return "Katerina"; }
        if i == 64 { return "Sofia"; }
        if i == 65 { return "Athina"; }
        if i == 66 { return "Ioanna"; }
        if i == 67 { return "Vasiliki"; }
        if i == 68 { return "Chrysoula"; }
        if i == 69 { return "Despina"; }
        if i == 70 { return "Elisabeth"; }
        if i == 71 { return "Katharina"; }
        if i == 72 { return "Barbara"; }
        if i == 73 { return "Andrea"; }
        if i == 74 { return "Julia"; }
        if i == 75 { return "Laura"; }
        if i == 76 { return "Sarah"; }
        if i == 77 { return "Anna"; }
        if i == 78 { return "Lisa"; }
        if i == 79 { return "Nina"; }
        if i == 80 { return "Celine"; }
        if i == 81 { return "Claire"; }
        if i == 82 { return "Lucie"; }
        if i == 83 { return "Manon"; }
        if i == 84 { return "Lea"; }
        if i == 85 { return "Juliette"; }
        if i == 86 { return "Alice"; }
        if i == 87 { return "Louise"; }
        if i == 88 { return "Chloe"; }
        if i == 89 { return "Ines"; }
        if i == 90 { return "Elena"; }
        if i == 91 { return "Giada"; }
        if i == 92 { return "Aurora"; }
        if i == 93 { return "Bianca"; }
        if i == 94 { return "Carlotta"; }
        if i == 95 { return "Benedetta"; }
        if i == 96 { return "Arianna"; }
        if i == 97 { return "Giorgia"; }
        if i == 98 { return "Lucia"; }
        if i == 99 { return "Paola"; }
        if i == 100 { return "Amelie"; }
        if i == 101 { return "Beatrix"; }
        if i == 102 { return "Delphine"; }
        if i == 103 { return "Elsa"; }
        if i == 104 { return "Hannelore"; }
        if i == 105 { return "Johanna"; }
        if i == 106 { return "Katarina"; }
        if i == 107 { return "Liesel"; }
        if i == 108 { return "Margot"; }
        if i == 109 { return "Noelle"; }
        if i == 110 { return "Ottilie"; }
        if i == 111 { return "Paloma"; }
        if i == 112 { return "Romy"; }
        if i == 113 { return "Therese"; }
        if i == 114 { return "Vivienne"; }
        if i == 115 { return "Wilhelmina"; }
        if i == 116 { return "Ynez"; }
        if i == 117 { return "Zelda"; }
        if i == 118 { return "Brigitta"; }
        if i == 119 { return "Dagmar"; }
        if i == 120 { return "Jutta"; }
        if i == 121 { return "Marlene"; }
        if i == 122 { return "Nadja"; }
        if i == 123 { return "Oriana"; }
        if i == 124 { return "Renate"; }
        if i == 125 { return "Solveig"; }
        if i == 126 { return "Tatiana"; }
        if i == 127 { return "Ulrike"; }
        if i == 128 { return "Veronique"; }
        if i == 129 { return "Wanda"; }
        if i == 130 { return "Yvette"; }
        if i == 131 { return "Zita"; }
        if i == 132 { return "Birgit"; }
        if i == 133 { return "Annegret"; }
        if i == 134 { return "Clothilde"; }
        if i == 135 { return "Donatella"; }
        if i == 136 { return "Edeltraud"; }
        if i == 137 { return "Fiorella"; }
        if i == 138 { return "Gunhild"; }
        if i == 139 { return "Henriette"; }
        if i == 140 { return "Immacolata"; }
        if i == 141 { return "Jorunn"; }
        if i == 142 { return "Kristiina"; }
        if i == 143 { return "Maddalena"; }
        if i == 144 { return "Nicoletta"; }
        if i == 145 { return "Ottavia"; }
        if i == 146 { return "Philippa"; }
        return "Ingrid";
    }

    public static func GetLastName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Mueller"; }
        if i == 1 { return "Schmidt"; }
        if i == 2 { return "Schneider"; }
        if i == 3 { return "Fischer"; }
        if i == 4 { return "Weber"; }
        if i == 5 { return "Meyer"; }
        if i == 6 { return "Wagner"; }
        if i == 7 { return "Becker"; }
        if i == 8 { return "Hoffmann"; }
        if i == 9 { return "Schulz"; }
        if i == 10 { return "Martin"; }
        if i == 11 { return "Bernard"; }
        if i == 12 { return "Dubois"; }
        if i == 13 { return "Thomas"; }
        if i == 14 { return "Robert"; }
        if i == 15 { return "Richard"; }
        if i == 16 { return "Petit"; }
        if i == 17 { return "Durand"; }
        if i == 18 { return "Leroy"; }
        if i == 19 { return "Moreau"; }
        if i == 20 { return "Rossi"; }
        if i == 21 { return "Russo"; }
        if i == 22 { return "Ferrari"; }
        if i == 23 { return "Esposito"; }
        if i == 24 { return "Bianchi"; }
        if i == 25 { return "Romano"; }
        if i == 26 { return "Colombo"; }
        if i == 27 { return "Ricci"; }
        if i == 28 { return "Marino"; }
        if i == 29 { return "Greco"; }
        if i == 30 { return "Silva"; }
        if i == 31 { return "Santos"; }
        if i == 32 { return "Ferreira"; }
        if i == 33 { return "Pereira"; }
        if i == 34 { return "Oliveira"; }
        if i == 35 { return "Costa"; }
        if i == 36 { return "Rodrigues"; }
        if i == 37 { return "Martins"; }
        if i == 38 { return "Sousa"; }
        if i == 39 { return "Fernandes"; }
        if i == 40 { return "Johansson"; }
        if i == 41 { return "Andersson"; }
        if i == 42 { return "Karlsson"; }
        if i == 43 { return "Nilsson"; }
        if i == 44 { return "Eriksson"; }
        if i == 45 { return "Larsson"; }
        if i == 46 { return "Olsson"; }
        if i == 47 { return "Persson"; }
        if i == 48 { return "Svensson"; }
        if i == 49 { return "Gustafsson"; }
        if i == 50 { return "De Vries"; }
        if i == 51 { return "Van den Berg"; }
        if i == 52 { return "Jansen"; }
        if i == 53 { return "De Groot"; }
        if i == 54 { return "Bakker"; }
        if i == 55 { return "Janssen"; }
        if i == 56 { return "Visser"; }
        if i == 57 { return "Smit"; }
        if i == 58 { return "Meijer"; }
        if i == 59 { return "De Boer"; }
        if i == 60 { return "Papadopoulos"; }
        if i == 61 { return "Papageorgiou"; }
        if i == 62 { return "Pappas"; }
        if i == 63 { return "Vlachos"; }
        if i == 64 { return "Nikolaidis"; }
        if i == 65 { return "Georgiou"; }
        if i == 66 { return "Antonopoulos"; }
        if i == 67 { return "Alexiou"; }
        if i == 68 { return "Constantinou"; }
        if i == 69 { return "Dimitriou"; }
        if i == 70 { return "Gruber"; }
        if i == 71 { return "Huber"; }
        if i == 72 { return "Bauer"; }
        if i == 73 { return "Pichler"; }
        if i == 74 { return "Steiner"; }
        if i == 75 { return "Moser"; }
        if i == 76 { return "Mayer"; }
        if i == 77 { return "Hofer"; }
        if i == 78 { return "Leitner"; }
        if i == 79 { return "Berger"; }
        if i == 80 { return "Laurent"; }
        if i == 81 { return "Simon"; }
        if i == 82 { return "Michel"; }
        if i == 83 { return "Lefebvre"; }
        if i == 84 { return "Lefevre"; }
        if i == 85 { return "Roux"; }
        if i == 86 { return "David"; }
        if i == 87 { return "Bertrand"; }
        if i == 88 { return "Morel"; }
        if i == 89 { return "Fournier"; }
        if i == 90 { return "Conte"; }
        if i == 91 { return "Galli"; }
        if i == 92 { return "Conti"; }
        if i == 93 { return "De Luca"; }
        if i == 94 { return "Mancini"; }
        if i == 95 { return "Barbieri"; }
        if i == 96 { return "Fontana"; }
        if i == 97 { return "Santoro"; }
        if i == 98 { return "Mariani"; }
        if i == 99 { return "Rinaldi"; }
        if i == 100 { return "Aldenberg"; }
        if i == 101 { return "Bertolini"; }
        if i == 102 { return "Castellano"; }
        if i == 103 { return "Dijkstra"; }
        if i == 104 { return "Falkenrath"; }
        if i == 105 { return "Grimaldi"; }
        if i == 106 { return "Iversen"; }
        if i == 107 { return "Kowalczyk"; }
        if i == 108 { return "Lindqvist"; }
        if i == 109 { return "Nystrom"; }
        if i == 110 { return "Obermann"; }
        if i == 111 { return "Paulsen"; }
        if i == 112 { return "Thorsen"; }
        if i == 113 { return "Uccello"; }
        if i == 114 { return "Vandenberg"; }
        if i == 115 { return "Wexler"; }
        if i == 116 { return "Ziegler"; }
        if i == 117 { return "Almqvist"; }
        if i == 118 { return "Bergstrom"; }
        if i == 119 { return "Dufresne"; }
        if i == 120 { return "Engel"; }
        if i == 121 { return "Fontaine"; }
        if i == 122 { return "Hartmann"; }
        if i == 123 { return "Ibsen"; }
        if i == 124 { return "Jorgensen"; }
        if i == 125 { return "Kessler"; }
        if i == 126 { return "Lombardi"; }
        if i == 127 { return "Neumann"; }
        if i == 128 { return "Ohlsson"; }
        if i == 129 { return "Pedersen"; }
        if i == 130 { return "Sorensen"; }
        if i == 131 { return "Toussaint"; }
        if i == 132 { return "Ulfsson"; }
        if i == 133 { return "Zimmermann"; }
        if i == 134 { return "Antonelli"; }
        if i == 135 { return "Clement"; }
        if i == 136 { return "DeVries"; }
        if i == 137 { return "Aakesson"; }
        if i == 138 { return "Battaglia"; }
        if i == 139 { return "Cavalcanti"; }
        if i == 140 { return "Delacroix"; }
        if i == 141 { return "Eichmann"; }
        if i == 142 { return "Ferrante"; }
        if i == 143 { return "Giordano"; }
        if i == 144 { return "Holmberg"; }
        if i == 145 { return "Ippolito"; }
        if i == 146 { return "Jansen-Berg"; }
        if i == 147 { return "Kirchner"; }
        if i == 148 { return "Lagerkvist"; }
        if i == 149 { return "Montanari"; }
        return "Mueller";
    }
}
