// Haitian Names - 100 male, 100 female, 100 last names
public abstract class KdspHaitianNames {

    public static func GetMaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Jean"; }
        if i == 1 { return "Pierre"; }
        if i == 2 { return "Jacques"; }
        if i == 3 { return "Michel"; }
        if i == 4 { return "Claude"; }
        if i == 5 { return "Frantz"; }
        if i == 6 { return "Toussaint"; }
        if i == 7 { return "Wilfred"; }
        if i == 8 { return "Edouard"; }
        if i == 9 { return "Rene"; }
        if i == 10 { return "Marcel"; }
        if i == 11 { return "Henri"; }
        if i == 12 { return "Louis"; }
        if i == 13 { return "Yves"; }
        if i == 14 { return "Phillipe"; }
        if i == 15 { return "Antoine"; }
        if i == 16 { return "Joseph"; }
        if i == 17 { return "Andre"; }
        if i == 18 { return "Bernard"; }
        if i == 19 { return "Christophe"; }
        if i == 20 { return "Daniel"; }
        if i == 21 { return "Emmanuel"; }
        if i == 22 { return "Fabrice"; }
        if i == 23 { return "Gerard"; }
        if i == 24 { return "Hugo"; }
        if i == 25 { return "Ismael"; }
        if i == 26 { return "Jude"; }
        if i == 27 { return "Kevin"; }
        if i == 28 { return "Lionel"; }
        if i == 29 { return "Maurice"; }
        if i == 30 { return "Nicolas"; }
        if i == 31 { return "Olivier"; }
        if i == 32 { return "Patrick"; }
        if i == 33 { return "Quincy"; }
        if i == 34 { return "Raymond"; }
        if i == 35 { return "Samuel"; }
        if i == 36 { return "Thierry"; }
        if i == 37 { return "Ulrick"; }
        if i == 38 { return "Victor"; }
        if i == 39 { return "Wilson"; }
        if i == 40 { return "Xavier"; }
        if i == 41 { return "Youri"; }
        if i == 42 { return "Zacharie"; }
        if i == 43 { return "Alain"; }
        if i == 44 { return "Benoit"; }
        if i == 45 { return "Charles"; }
        if i == 46 { return "Dieudonne"; }
        if i == 47 { return "Etienne"; }
        if i == 48 { return "Fernand"; }
        if i == 49 { return "Gaston"; }
        if i == 50 { return "Herve"; }
        if i == 51 { return "Ignace"; }
        if i == 52 { return "Jules"; }
        if i == 53 { return "Karl"; }
        if i == 54 { return "Lucien"; }
        if i == 55 { return "Maxime"; }
        if i == 56 { return "Narcisse"; }
        if i == 57 { return "Octave"; }
        if i == 58 { return "Pascal"; }
        if i == 59 { return "Roland"; }
        if i == 60 { return "Serge"; }
        if i == 61 { return "Theodore"; }
        if i == 62 { return "Urbain"; }
        if i == 63 { return "Valentin"; }
        if i == 64 { return "Willy"; }
        if i == 65 { return "Yvon"; }
        if i == 66 { return "Zephirin"; }
        if i == 67 { return "Alix"; }
        if i == 68 { return "Bruno"; }
        if i == 69 { return "Camille"; }
        if i == 70 { return "Denis"; }
        if i == 71 { return "Elias"; }
        if i == 72 { return "Felix"; }
        if i == 73 { return "Gilbert"; }
        if i == 74 { return "Hector"; }
        if i == 75 { return "Ivan"; }
        if i == 76 { return "Joel"; }
        if i == 77 { return "Kenny"; }
        if i == 78 { return "Laurent"; }
        if i == 79 { return "Marc"; }
        if i == 80 { return "Nestor"; }
        if i == 81 { return "Oscar"; }
        if i == 82 { return "Paul"; }
        if i == 83 { return "Raoul"; }
        if i == 84 { return "Sylvain"; }
        if i == 85 { return "Timothee"; }
        if i == 86 { return "Ulysse"; }
        if i == 87 { return "Vladimir"; }
        if i == 88 { return "Wadner"; }
        if i == 89 { return "Yannick"; }
        if i == 90 { return "Zidane"; }
        if i == 91 { return "Armand"; }
        if i == 92 { return "Baptiste"; }
        if i == 93 { return "Celestin"; }
        if i == 94 { return "Dominique"; }
        if i == 95 { return "Ernst"; }
        if i == 96 { return "Francois"; }
        if i == 97 { return "Gervais"; }
        if i == 98 { return "Hyppolite"; }
        if i == 99 { return "Innocent"; }
        if i == 100 { return "Jean-Baptiste"; }
        if i == 101 { return "Wilner"; }
        if i == 102 { return "Ghislain"; }
        if i == 103 { return "Herold"; }
        if i == 104 { return "Kervens"; }
        if i == 105 { return "Luckner"; }
        if i == 106 { return "Makenson"; }
        if i == 107 { return "Nerlande"; }
        if i == 108 { return "Odelin"; }
        if i == 109 { return "Pierrot"; }
        if i == 110 { return "Renel"; }
        if i == 111 { return "Ti-Jean"; }
        if i == 112 { return "Venel"; }
        if i == 113 { return "Wesley"; }
        if i == 114 { return "Berthony"; }
        if i == 115 { return "Clervil"; }
        if i == 116 { return "Duckens"; }
        if i == 117 { return "Fritznel"; }
        if i == 118 { return "Guerson"; }
        if i == 119 { return "Herby"; }
        if i == 120 { return "Islande"; }
        if i == 121 { return "Jameson"; }
        if i == 122 { return "Kenley"; }
        if i == 123 { return "Michelet"; }
        if i == 124 { return "Nesly"; }
        if i == 125 { return "Olriche"; }
        if i == 126 { return "Peterson"; }
        if i == 127 { return "Ricardo"; }
        if i == 128 { return "Stanley"; }
        if i == 129 { return "Thelusma"; }
        if i == 130 { return "Uriel"; }
        if i == 131 { return "Vilaire"; }
        if i == 132 { return "Watson"; }
        if i == 133 { return "Yverose"; }
        if i == 134 { return "Belony"; }
        if i == 135 { return "Charlot"; }
        if i == 136 { return "Dukens"; }
        if i == 137 { return "Evens"; }
        if i == 138 { return "Jocelyn"; }
        if i == 139 { return "Kesner"; }
        if i == 140 { return "Lesly"; }
        if i == 141 { return "Maxo"; }
        if i == 142 { return "Nixon"; }
        if i == 143 { return "Obed"; }
        if i == 144 { return "Pradel"; }
        if i == 145 { return "Robenson"; }
        if i == 146 { return "Sonson"; }
        if i == 147 { return "Ti-Roro"; }
        if i == 148 { return "Wilguens"; }
        if i == 149 { return "Yvenson"; }
        return "Jean";
    }

    public static func GetFemaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Marie"; }
        if i == 1 { return "Madeleine"; }
        if i == 2 { return "Simone"; }
        if i == 3 { return "Nadine"; }
        if i == 4 { return "Claudette"; }
        if i == 5 { return "Rosalie"; }
        if i == 6 { return "Guerda"; }
        if i == 7 { return "Jeanne"; }
        if i == 8 { return "Yanick"; }
        if i == 9 { return "Mirlande"; }
        if i == 10 { return "Marlene"; }
        if i == 11 { return "Bernadette"; }
        if i == 12 { return "Carole"; }
        if i == 13 { return "Denise"; }
        if i == 14 { return "Elisabeth"; }
        if i == 15 { return "Francoise"; }
        if i == 16 { return "Gertrude"; }
        if i == 17 { return "Helene"; }
        if i == 18 { return "Irene"; }
        if i == 19 { return "Josette"; }
        if i == 20 { return "Ketty"; }
        if i == 21 { return "Lucienne"; }
        if i == 22 { return "Martine"; }
        if i == 23 { return "Nathalie"; }
        if i == 24 { return "Odette"; }
        if i == 25 { return "Paulette"; }
        if i == 26 { return "Rachelle"; }
        if i == 27 { return "Suzanne"; }
        if i == 28 { return "Therese"; }
        if i == 29 { return "Violette"; }
        if i == 30 { return "Yolande"; }
        if i == 31 { return "Zita"; }
        if i == 32 { return "Adrienne"; }
        if i == 33 { return "Beatrice"; }
        if i == 34 { return "Carmelle"; }
        if i == 35 { return "Daphne"; }
        if i == 36 { return "Edwidge"; }
        if i == 37 { return "Fabienne"; }
        if i == 38 { return "Gisele"; }
        if i == 39 { return "Henriette"; }
        if i == 40 { return "Isabelle"; }
        if i == 41 { return "Jacqueline"; }
        if i == 42 { return "Katiana"; }
        if i == 43 { return "Louisiane"; }
        if i == 44 { return "Magalie"; }
        if i == 45 { return "Naomi"; }
        if i == 46 { return "Oline"; }
        if i == 47 { return "Patricia"; }
        if i == 48 { return "Regine"; }
        if i == 49 { return "Solange"; }
        if i == 50 { return "Tatiana"; }
        if i == 51 { return "Ursule"; }
        if i == 52 { return "Veronika"; }
        if i == 53 { return "Wideline"; }
        if i == 54 { return "Yvette"; }
        if i == 55 { return "Zephirine"; }
        if i == 56 { return "Aimee"; }
        if i == 57 { return "Brigitte"; }
        if i == 58 { return "Cecile"; }
        if i == 59 { return "Dieula"; }
        if i == 60 { return "Emilie"; }
        if i == 61 { return "Fabiola"; }
        if i == 62 { return "Ginette"; }
        if i == 63 { return "Hermine"; }
        if i == 64 { return "Idaline"; }
        if i == 65 { return "Jocelyne"; }
        if i == 66 { return "Kerline"; }
        if i == 67 { return "Lourdes"; }
        if i == 68 { return "Micheline"; }
        if i == 69 { return "Nicaise"; }
        if i == 70 { return "Olympia"; }
        if i == 71 { return "Pascale"; }
        if i == 72 { return "Rose"; }
        if i == 73 { return "Stephanie"; }
        if i == 74 { return "Thamar"; }
        if i == 75 { return "Ulda"; }
        if i == 76 { return "Viergina"; }
        if i == 77 { return "Widelene"; }
        if i == 78 { return "Yolette"; }
        if i == 79 { return "Zora"; }
        if i == 80 { return "Angeline"; }
        if i == 81 { return "Benita"; }
        if i == 82 { return "Charlene"; }
        if i == 83 { return "Darlene"; }
        if i == 84 { return "Edeline"; }
        if i == 85 { return "Fleurette"; }
        if i == 86 { return "Guerline"; }
        if i == 87 { return "Hermione"; }
        if i == 88 { return "Imelda"; }
        if i == 89 { return "Judith"; }
        if i == 90 { return "Katleen"; }
        if i == 91 { return "Lamercie"; }
        if i == 92 { return "Mirlanda"; }
        if i == 93 { return "Nerlande"; }
        if i == 94 { return "Olga"; }
        if i == 95 { return "Phara"; }
        if i == 96 { return "Rosemonde"; }
        if i == 97 { return "Sherline"; }
        if i == 98 { return "Tulie"; }
        if i == 99 { return "Venise"; }
        if i == 100 { return "Marie-Ange"; }
        if i == 101 { return "Darline"; }
        if i == 102 { return "Esperancia"; }
        if i == 103 { return "Herlande"; }
        if i == 104 { return "Islande"; }
        if i == 105 { return "Jesula"; }
        if i == 106 { return "Kettelie"; }
        if i == 107 { return "Lovelie"; }
        if i == 108 { return "Nadege"; }
        if i == 109 { return "Ophelia"; }
        if i == 110 { return "Rosemene"; }
        if i == 111 { return "Tamara"; }
        if i == 112 { return "Vierge"; }
        if i == 113 { return "Wisline"; }
        if i == 114 { return "Altagrace"; }
        if i == 115 { return "Clorinde"; }
        if i == 116 { return "Elifaite"; }
        if i == 117 { return "Francine"; }
        if i == 118 { return "Gerty"; }
        if i == 119 { return "Immacula"; }
        if i == 120 { return "Ketsia"; }
        if i == 121 { return "Magdala"; }
        if i == 122 { return "Naomie"; }
        if i == 123 { return "Roseline"; }
        if i == 124 { return "Tirzah"; }
        if i == 125 { return "Wendie"; }
        if i == 126 { return "Yanique"; }
        if i == 127 { return "Adeline"; }
        if i == 128 { return "Carline"; }
        if i == 129 { return "Mirlene"; }
        if i == 130 { return "Naphtalie"; }
        if i == 131 { return "Ostania"; }
        if i == 132 { return "Phanya"; }
        if i == 133 { return "Rosemitha"; }
        if i == 134 { return "Sherlie"; }
        if i == 135 { return "Tania-Rose"; }
        if i == 136 { return "Vania"; }
        if i == 137 { return "Youseline"; }
        if i == 138 { return "Adlyne"; }
        if i == 139 { return "Bethsaida"; }
        if i == 140 { return "Clautide"; }
        if i == 141 { return "Dieunette"; }
        if i == 142 { return "Elmithe"; }
        if i == 143 { return "Fabiana"; }
        if i == 144 { return "Guettie"; }
        if i == 145 { return "Herline"; }
        if i == 146 { return "Ionie"; }
        if i == 147 { return "Jesumene"; }
        if i == 148 { return "Ketleine"; }
        if i == 149 { return "Lourdemie"; }
        return "Marie";
    }

    public static func GetLastName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Jean-Baptiste"; }
        if i == 1 { return "Desrosiers"; }
        if i == 2 { return "Pierre-Louis"; }
        if i == 3 { return "Duvalier"; }
        if i == 4 { return "Celestin"; }
        if i == 5 { return "Beauvoir"; }
        if i == 6 { return "Joseph"; }
        if i == 7 { return "Toussaint"; }
        if i == 8 { return "Louverture"; }
        if i == 9 { return "Saint-Louis"; }
        if i == 10 { return "Aristide"; }
        if i == 11 { return "Bellegarde"; }
        if i == 12 { return "Casimir"; }
        if i == 13 { return "Dessalines"; }
        if i == 14 { return "Estimé"; }
        if i == 15 { return "Fanfan"; }
        if i == 16 { return "Guillaume"; }
        if i == 17 { return "Hyppolite"; }
        if i == 18 { return "Innocent"; }
        if i == 19 { return "Jean-Pierre"; }
        if i == 20 { return "Kernisant"; }
        if i == 21 { return "Lafortune"; }
        if i == 22 { return "Magloire"; }
        if i == 23 { return "Napoleon"; }
        if i == 24 { return "Orélien"; }
        if i == 25 { return "Pétion"; }
        if i == 26 { return "Romain"; }
        if i == 27 { return "Saint-Jean"; }
        if i == 28 { return "Thermidor"; }
        if i == 29 { return "Ulysse"; }
        if i == 30 { return "Vincent"; }
        if i == 31 { return "Wyclef"; }
        if i == 32 { return "Yvon"; }
        if i == 33 { return "Zéphirin"; }
        if i == 34 { return "Alexandre"; }
        if i == 35 { return "Boukman"; }
        if i == 36 { return "Christophe"; }
        if i == 37 { return "Dorceus"; }
        if i == 38 { return "Etienne"; }
        if i == 39 { return "Francois"; }
        if i == 40 { return "Geffrard"; }
        if i == 41 { return "Hérard"; }
        if i == 42 { return "Inginac"; }
        if i == 43 { return "Jean-Louis"; }
        if i == 44 { return "Kébreau"; }
        if i == 45 { return "Lescot"; }
        if i == 46 { return "Martelly"; }
        if i == 47 { return "Namphy"; }
        if i == 48 { return "Ovide"; }
        if i == 49 { return "Préval"; }
        if i == 50 { return "Qualo"; }
        if i == 51 { return "Rigaud"; }
        if i == 52 { return "Sam"; }
        if i == 53 { return "Théard"; }
        if i == 54 { return "Ultino"; }
        if i == 55 { return "Vastey"; }
        if i == 56 { return "Wesner"; }
        if i == 57 { return "Youri"; }
        if i == 58 { return "Zamor"; }
        if i == 59 { return "Auguste"; }
        if i == 60 { return "Bazile"; }
        if i == 61 { return "Clervaux"; }
        if i == 62 { return "Delmas"; }
        if i == 63 { return "Emmanuel"; }
        if i == 64 { return "Fleury"; }
        if i == 65 { return "Gilles"; }
        if i == 66 { return "Honorat"; }
        if i == 67 { return "Isidore"; }
        if i == 68 { return "Janvier"; }
        if i == 69 { return "Kernizan"; }
        if i == 70 { return "Lafontant"; }
        if i == 71 { return "Moreau"; }
        if i == 72 { return "Nazaire"; }
        if i == 73 { return "Olivier"; }
        if i == 74 { return "Paul"; }
        if i == 75 { return "Remy"; }
        if i == 76 { return "Sylvestre"; }
        if i == 77 { return "Tassy"; }
        if i == 78 { return "Ulrick"; }
        if i == 79 { return "Verdieu"; }
        if i == 80 { return "Wilner"; }
        if i == 81 { return "Yolette"; }
        if i == 82 { return "Zétrenne"; }
        if i == 83 { return "André"; }
        if i == 84 { return "Bélizaire"; }
        if i == 85 { return "Cadet"; }
        if i == 86 { return "Ducasse"; }
        if i == 87 { return "Edmond"; }
        if i == 88 { return "Fortune"; }
        if i == 89 { return "Gaspard"; }
        if i == 90 { return "Hercule"; }
        if i == 91 { return "Ileus"; }
        if i == 92 { return "Jerome"; }
        if i == 93 { return "Kenol"; }
        if i == 94 { return "Laguerre"; }
        if i == 95 { return "Michel"; }
        if i == 96 { return "Noël"; }
        if i == 97 { return "Pierre"; }
        if i == 98 { return "Raymond"; }
        if i == 99 { return "Simon"; }
        if i == 100 { return "Baptiste"; }
        if i == 101 { return "Charlemagne"; }
        if i == 102 { return "Metellus"; }
        if i == 103 { return "Noel"; }
        if i == 104 { return "Occilien"; }
        if i == 105 { return "Petit-Frere"; }
        if i == 106 { return "Telemaque"; }
        if i == 107 { return "Belizaire"; }
        if i == 108 { return "Casseus"; }
        if i == 109 { return "Delva"; }
        if i == 110 { return "Estime"; }
        if i == 111 { return "Fleurant"; }
        if i == 112 { return "Germain"; }
        if i == 113 { return "Isidor"; }
        if i == 114 { return "Michaud"; }
        if i == 115 { return "Narcisse"; }
        if i == 116 { return "Oriol"; }
        if i == 117 { return "Pascal"; }
        if i == 118 { return "Registre"; }
        if i == 119 { return "Severe"; }
        if i == 120 { return "Théodore"; }
        if i == 121 { return "Valcin"; }
        if i == 122 { return "Wagnac"; }
        if i == 123 { return "Yves"; }
        if i == 124 { return "Achille"; }
        if i == 125 { return "Bonhomme"; }
        if i == 126 { return "Dorsainvil"; }
        if i == 127 { return "Exantus"; }
        if i == 128 { return "Faustin"; }
        if i == 129 { return "Hilaire"; }
        if i == 130 { return "Delatour"; }
        if i == 131 { return "Estiverne"; }
        if i == 132 { return "Fenelon"; }
        if i == 133 { return "Guirand"; }
        if i == 134 { return "Jean-Gilles"; }
        if i == 135 { return "Lamothe"; }
        if i == 136 { return "Milfort"; }
        if i == 137 { return "Occeus"; }
        if i == 138 { return "Previlon"; }
        if i == 139 { return "Similien"; }
        if i == 140 { return "Toussaint-Louis"; }
        if i == 141 { return "Verella"; }
        if i == 142 { return "Zephir"; }
        if i == 143 { return "Almonor"; }
        if i == 144 { return "Beauplan"; }
        if i == 145 { return "Clerveaux"; }
        if i == 146 { return "Desir"; }
        if i == 147 { return "Emile"; }
        if i == 148 { return "Filsaime"; }
        if i == 149 { return "Gustave"; }
        return "Jean-Baptiste";
    }
}
