// Japanese Names - 100 male, 100 female, 100 last names
public abstract class KdspJapaneseNames {

    public static func GetMaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Hiroshi"; }
        if i == 1 { return "Takeshi"; }
        if i == 2 { return "Kenji"; }
        if i == 3 { return "Satoshi"; }
        if i == 4 { return "Yuki"; }
        if i == 5 { return "Kazuki"; }
        if i == 6 { return "Daiki"; }
        if i == 7 { return "Ryota"; }
        if i == 8 { return "Shota"; }
        if i == 9 { return "Yuto"; }
        if i == 10 { return "Haruki"; }
        if i == 11 { return "Kenta"; }
        if i == 12 { return "Taro"; }
        if i == 13 { return "Jiro"; }
        if i == 14 { return "Saburo"; }
        if i == 15 { return "Ichiro"; }
        if i == 16 { return "Akira"; }
        if i == 17 { return "Ryu"; }
        if i == 18 { return "Ken"; }
        if i == 19 { return "Shin"; }
        if i == 20 { return "Masa"; }
        if i == 21 { return "Koji"; }
        if i == 22 { return "Tetsuya"; }
        if i == 23 { return "Naoki"; }
        if i == 24 { return "Makoto"; }
        if i == 25 { return "Sho"; }
        if i == 26 { return "Ren"; }
        if i == 27 { return "Hayato"; }
        if i == 28 { return "Kaito"; }
        if i == 29 { return "Sosuke"; }
        if i == 30 { return "Yamato"; }
        if i == 31 { return "Hiro"; }
        if i == 32 { return "Goro"; }
        if i == 33 { return "Masato"; }
        if i == 34 { return "Noboru"; }
        if i == 35 { return "Shinji"; }
        if i == 36 { return "Takumi"; }
        if i == 37 { return "Yuji"; }
        if i == 38 { return "Katsu"; }
        if i == 39 { return "Isamu"; }
        if i == 40 { return "Hideki"; }
        if i == 41 { return "Toshiro"; }
        if i == 42 { return "Koichi"; }
        if i == 43 { return "Daisuke"; }
        if i == 44 { return "Shingo"; }
        if i == 45 { return "Kentaro"; }
        if i == 46 { return "Ryuji"; }
        if i == 47 { return "Tatsuya"; }
        if i == 48 { return "Yusuke"; }
        if i == 49 { return "Kensuke"; }
        if i == 50 { return "Seiji"; }
        if i == 51 { return "Akihiro"; }
        if i == 52 { return "Minoru"; }
        if i == 53 { return "Osamu"; }
        if i == 54 { return "Sora"; }
        if i == 55 { return "Hikaru"; }
        if i == 56 { return "Shun"; }
        if i == 57 { return "Yuma"; }
        if i == 58 { return "Riku"; }
        if i == 59 { return "Taichi"; }
        if i == 60 { return "Kazuya"; }
        if i == 61 { return "Natsuki"; }
        if i == 62 { return "Shiro"; }
        if i == 63 { return "Genji"; }
        if i == 64 { return "Hanzo"; }
        if i == 65 { return "Kisho"; }
        if i == 66 { return "Mitsuru"; }
        if i == 67 { return "Raiden"; }
        if i == 68 { return "Tadashi"; }
        if i == 69 { return "Yoshio"; }
        if i == 70 { return "Atsushi"; }
        if i == 71 { return "Fumio"; }
        if i == 72 { return "Hajime"; }
        if i == 73 { return "Jin"; }
        if i == 74 { return "Katsuro"; }
        if i == 75 { return "Mamoru"; }
        if i == 76 { return "Nobuo"; }
        if i == 77 { return "Takashi"; }
        if i == 78 { return "Wataru"; }
        if i == 79 { return "Yasuo"; }
        if i == 80 { return "Akio"; }
        if i == 81 { return "Benjiro"; }
        if i == 82 { return "Chiaki"; }
        if i == 83 { return "Eiji"; }
        if i == 84 { return "Genta"; }
        if i == 85 { return "Haruto"; }
        if i == 86 { return "Itsuki"; }
        if i == 87 { return "Junichi"; }
        if i == 88 { return "Kenzo"; }
        if i == 89 { return "Leo"; }
        if i == 90 { return "Masashi"; }
        if i == 91 { return "Naoto"; }
        if i == 92 { return "Ryo"; }
        if i == 93 { return "Shuichi"; }
        if i == 94 { return "Tsubasa"; }
        if i == 95 { return "Yukio"; }
        if i == 96 { return "Zen"; }
        if i == 97 { return "Arata"; }
        if i == 98 { return "Daigo"; }
        if i == 99 { return "Fumihiro"; }
        if i == 100 { return "Akihiko"; }
        if i == 101 { return "Chikara"; }
        if i == 102 { return "Hachiro"; }
        if i == 103 { return "Isao"; }
        if i == 104 { return "Katsuo"; }
        if i == 105 { return "Kiyoshi"; }
        if i == 106 { return "Masaru"; }
        if i == 107 { return "Ryoichi"; }
        if i == 108 { return "Shigeru"; }
        if i == 109 { return "Umeji"; }
        if i == 110 { return "Yasuhiro"; }
        if i == 111 { return "Zenjiro"; }
        if i == 112 { return "Chojiro"; }
        if i == 113 { return "Eisuke"; }
        if i == 114 { return "Fujio"; }
        if i == 115 { return "Hideaki"; }
        if i == 116 { return "Kohei"; }
        if i == 117 { return "Reiji"; }
        if i == 118 { return "Satoru"; }
        if i == 119 { return "Yoshinori"; }
        if i == 120 { return "Akinori"; }
        if i == 121 { return "Chuichi"; }
        if i == 122 { return "Etsuo"; }
        if i == 123 { return "Fuminori"; }
        if i == 124 { return "Gengo"; }
        if i == 125 { return "Hirofumi"; }
        if i == 126 { return "Issei"; }
        if i == 127 { return "Junpei"; }
        if i == 128 { return "Katsuhiro"; }
        if i == 129 { return "Kiichi"; }
        if i == 130 { return "Masaaki"; }
        if i == 131 { return "Norio"; }
        if i == 132 { return "Shohei"; }
        if i == 133 { return "Shigenori"; }
        if i == 134 { return "Tomohiro"; }
        if i == 135 { return "Umetaro"; }
        if i == 136 { return "Yasutaka"; }
        if i == 137 { return "Zenkichi"; }
        if i == 138 { return "Arihiro"; }
        if i == 139 { return "Chikashi"; }
        if i == 140 { return "Eijiro"; }
        if i == 141 { return "Fumitaka"; }
        if i == 142 { return "Gonbei"; }
        if i == 143 { return "Hidetoshi"; }
        if i == 144 { return "Ikuo"; }
        if i == 145 { return "Junzo"; }
        if i == 146 { return "Katsutoshi"; }
        if i == 147 { return "Kiyotaka"; }
        if i == 148 { return "Masanobu"; }
        if i == 149 { return "Norihiko"; }
        return "Kenji";
    }

    public static func GetFemaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 148);
        if i == 0 { return "Yuki"; }
        if i == 1 { return "Sakura"; }
        if i == 2 { return "Hana"; }
        if i == 3 { return "Aiko"; }
        if i == 4 { return "Mei"; }
        if i == 5 { return "Yui"; }
        if i == 6 { return "Rin"; }
        if i == 7 { return "Mio"; }
        if i == 8 { return "Akane"; }
        if i == 9 { return "Haruka"; }
        if i == 10 { return "Ayumi"; }
        if i == 11 { return "Riko"; }
        if i == 12 { return "Nana"; }
        if i == 13 { return "Saki"; }
        if i == 14 { return "Mika"; }
        if i == 15 { return "Yoko"; }
        if i == 16 { return "Keiko"; }
        if i == 17 { return "Emiko"; }
        if i == 18 { return "Noriko"; }
        if i == 19 { return "Mariko"; }
        if i == 20 { return "Naomi"; }
        if i == 21 { return "Tomoko"; }
        if i == 22 { return "Fumiko"; }
        if i == 23 { return "Michiko"; }
        if i == 24 { return "Akiko"; }
        if i == 25 { return "Yumiko"; }
        if i == 26 { return "Aya"; }
        if i == 27 { return "Mai"; }
        if i == 28 { return "Misaki"; }
        if i == 29 { return "Nanami"; }
        if i == 30 { return "Hinata"; }
        if i == 31 { return "Koharu"; }
        if i == 32 { return "Honoka"; }
        if i == 33 { return "Shiori"; }
        if i == 34 { return "Miyu"; }
        if i == 35 { return "Kana"; }
        if i == 36 { return "Asuka"; }
        if i == 37 { return "Sayuri"; }
        if i == 38 { return "Midori"; }
        if i == 39 { return "Kaori"; }
        if i == 40 { return "Hitomi"; }
        if i == 41 { return "Megumi"; }
        if i == 42 { return "Chihiro"; }
        if i == 43 { return "Emi"; }
        if i == 44 { return "Yuna"; }
        if i == 45 { return "Kanna"; }
        if i == 46 { return "Rei"; }
        if i == 47 { return "Sora"; }
        if i == 48 { return "Kotone"; }
        if i == 49 { return "Hikari"; }
        if i == 50 { return "Reina"; }
        if i == 51 { return "Mana"; }
        if i == 52 { return "Rena"; }
        if i == 53 { return "Yua"; }
        if i == 54 { return "Sara"; }
        if i == 55 { return "Moe"; }
        if i == 56 { return "Nina"; }
        if i == 57 { return "Hina"; }
        if i == 58 { return "Kokoro"; }
        if i == 59 { return "Nozomi"; }
        if i == 60 { return "Miyuki"; }
        if i == 61 { return "Chiyo"; }
        if i == 62 { return "Sumiko"; }
        if i == 63 { return "Junko"; }
        if i == 64 { return "Reiko"; }
        if i == 65 { return "Sachiko"; }
        if i == 66 { return "Masako"; }
        if i == 67 { return "Kazuko"; }
        if i == 68 { return "Takako"; }
        if i == 69 { return "Kyoko"; }
        if i == 70 { return "Yasuko"; }
        if i == 71 { return "Erika"; }
        if i == 72 { return "Mayu"; }
        if i == 73 { return "Natsumi"; }
        if i == 74 { return "Kanon"; }
        if i == 75 { return "Aoi"; }
        if i == 76 { return "Rio"; }
        if i == 77 { return "Sana"; }
        if i == 78 { return "Tsubaki"; }
        if i == 79 { return "Hotaru"; }
        if i == 80 { return "Izumi"; }
        if i == 81 { return "Kasumi"; }
        if i == 82 { return "Momoka"; }
        if i == 83 { return "Yuri"; }
        if i == 84 { return "Ai"; }
        if i == 85 { return "Chika"; }
        if i == 86 { return "Haru"; }
        if i == 87 { return "Kaho"; }
        if i == 88 { return "Miku"; }
        if i == 89 { return "Rika"; }
        if i == 90 { return "Shizuka"; }
        if i == 91 { return "Tomo"; }
        if i == 92 { return "Wakana"; }
        if i == 93 { return "Yuzuki"; }
        if i == 94 { return "Ami"; }
        if i == 95 { return "Hoshi"; }
        if i == 96 { return "Kira"; }
        if i == 97 { return "Luna"; }
        if i == 98 { return "Tsuki"; }
        if i == 99 { return "Yume"; }
        if i == 100 { return "Akemi"; }
        if i == 101 { return "Hanako"; }
        if i == 102 { return "Kimiko"; }
        if i == 103 { return "Machiko"; }
        if i == 104 { return "Natsuki"; }
        if i == 105 { return "Umeko"; }
        if i == 106 { return "Ayame"; }
        if i == 107 { return "Chinatsu"; }
        if i == 108 { return "Eriko"; }
        if i == 109 { return "Fuyuko"; }
        if i == 110 { return "Harumi"; }
        if i == 111 { return "Ikuko"; }
        if i == 112 { return "Kanako"; }
        if i == 113 { return "Kiyomi"; }
        if i == 114 { return "Nobuko"; }
        if i == 115 { return "Rieko"; }
        if i == 116 { return "Satomi"; }
        if i == 117 { return "Tomoe"; }
        if i == 118 { return "Yoshie"; }
        if i == 119 { return "Asami"; }
        if i == 120 { return "Chieko"; }
        if i == 121 { return "Etsuko"; }
        if i == 122 { return "Fusae"; }
        if i == 123 { return "Hatsue"; }
        if i == 124 { return "Itsuko"; }
        if i == 125 { return "Katsuko"; }
        if i == 126 { return "Kumiko"; }
        if i == 127 { return "Masae"; }
        if i == 128 { return "Ryoko"; }
        if i == 129 { return "Toshiko"; }
        if i == 130 { return "Yayoi"; }
        if i == 131 { return "Yuriko"; }
        if i == 132 { return "Ayano"; }
        if i == 133 { return "Ayaka-Rin"; }
        if i == 134 { return "Chisato"; }
        if i == 135 { return "Emiri"; }
        if i == 136 { return "Fujiko"; }
        if i == 137 { return "Hatsumi"; }
        if i == 138 { return "Ikumi"; }
        if i == 139 { return "Kaname"; }
        if i == 140 { return "Mayumi"; }
        if i == 141 { return "Rinko"; }
        if i == 142 { return "Sakiko"; }
        if i == 143 { return "Tamiko"; }
        if i == 144 { return "Utako"; }
        if i == 145 { return "Yasue"; }
        if i == 146 { return "Yumiko-Rei"; }
        if i == 147 { return "Azusa"; }
        return "Sakura";
    }

    public static func GetLastName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Tanaka"; }
        if i == 1 { return "Yamamoto"; }
        if i == 2 { return "Watanabe"; }
        if i == 3 { return "Suzuki"; }
        if i == 4 { return "Takahashi"; }
        if i == 5 { return "Sato"; }
        if i == 6 { return "Ito"; }
        if i == 7 { return "Nakamura"; }
        if i == 8 { return "Kobayashi"; }
        if i == 9 { return "Kato"; }
        if i == 10 { return "Yoshida"; }
        if i == 11 { return "Yamada"; }
        if i == 12 { return "Sasaki"; }
        if i == 13 { return "Yamaguchi"; }
        if i == 14 { return "Matsumoto"; }
        if i == 15 { return "Inoue"; }
        if i == 16 { return "Kimura"; }
        if i == 17 { return "Hayashi"; }
        if i == 18 { return "Shimizu"; }
        if i == 19 { return "Yamazaki"; }
        if i == 20 { return "Mori"; }
        if i == 21 { return "Abe"; }
        if i == 22 { return "Ikeda"; }
        if i == 23 { return "Hashimoto"; }
        if i == 24 { return "Ishikawa"; }
        if i == 25 { return "Yamashita"; }
        if i == 26 { return "Ogawa"; }
        if i == 27 { return "Ishii"; }
        if i == 28 { return "Hasegawa"; }
        if i == 29 { return "Goto"; }
        if i == 30 { return "Okada"; }
        if i == 31 { return "Kondo"; }
        if i == 32 { return "Maeda"; }
        if i == 33 { return "Fujita"; }
        if i == 34 { return "Endo"; }
        if i == 35 { return "Aoki"; }
        if i == 36 { return "Sakamoto"; }
        if i == 37 { return "Murakami"; }
        if i == 38 { return "Fukuda"; }
        if i == 39 { return "Ota"; }
        if i == 40 { return "Nishimura"; }
        if i == 41 { return "Fujii"; }
        if i == 42 { return "Okamoto"; }
        if i == 43 { return "Matsuda"; }
        if i == 44 { return "Nakagawa"; }
        if i == 45 { return "Fujiwara"; }
        if i == 46 { return "Miura"; }
        if i == 47 { return "Nakano"; }
        if i == 48 { return "Hara"; }
        if i == 49 { return "Takeuchi"; }
        if i == 50 { return "Kaneko"; }
        if i == 51 { return "Wada"; }
        if i == 52 { return "Nakajima"; }
        if i == 53 { return "Ishida"; }
        if i == 54 { return "Ueda"; }
        if i == 55 { return "Morita"; }
        if i == 56 { return "Harada"; }
        if i == 57 { return "Saito"; }
        if i == 58 { return "Sugiyama"; }
        if i == 59 { return "Tamura"; }
        if i == 60 { return "Kawamura"; }
        if i == 61 { return "Otsuka"; }
        if i == 62 { return "Chiba"; }
        if i == 63 { return "Kubo"; }
        if i == 64 { return "Matsui"; }
        if i == 65 { return "Iwasaki"; }
        if i == 66 { return "Sakurai"; }
        if i == 67 { return "Kinoshita"; }
        if i == 68 { return "Noguchi"; }
        if i == 69 { return "Matsuo"; }
        if i == 70 { return "Nomura"; }
        if i == 71 { return "Kikuchi"; }
        if i == 72 { return "Sano"; }
        if i == 73 { return "Onishi"; }
        if i == 74 { return "Sugawara"; }
        if i == 75 { return "Arai"; }
        if i == 76 { return "Hirano"; }
        if i == 77 { return "Kawasaki"; }
        if i == 78 { return "Kojima"; }
        if i == 79 { return "Uchida"; }
        if i == 80 { return "Ando"; }
        if i == 81 { return "Miyamoto"; }
        if i == 82 { return "Takagi"; }
        if i == 83 { return "Taniguchi"; }
        if i == 84 { return "Oishi"; }
        if i == 85 { return "Ueno"; }
        if i == 86 { return "Naito"; }
        if i == 87 { return "Maruyama"; }
        if i == 88 { return "Imai"; }
        if i == 89 { return "Takada"; }
        if i == 90 { return "Hirata"; }
        if i == 91 { return "Koyama"; }
        if i == 92 { return "Fuji"; }
        if i == 93 { return "Ozawa"; }
        if i == 94 { return "Miyazaki"; }
        if i == 95 { return "Nishida"; }
        if i == 96 { return "Hamada"; }
        if i == 97 { return "Honda"; }
        if i == 98 { return "Katayama"; }
        if i == 99 { return "Tsuchiya"; }
        if i == 100 { return "Akiyama"; }
        if i == 101 { return "Kanda"; }
        if i == 102 { return "Kubota"; }
        if i == 103 { return "Taguchi"; }
        if i == 104 { return "Doi"; }
        if i == 105 { return "Kawaguchi"; }
        if i == 106 { return "Kudo"; }
        if i == 107 { return "Yokoyama"; }
        if i == 108 { return "Ebina"; }
        if i == 109 { return "Furukawa"; }
        if i == 110 { return "Kurokawa"; }
        if i == 111 { return "Ohashi"; }
        if i == 112 { return "Ono"; }
        if i == 113 { return "Asano"; }
        if i == 114 { return "Eguchi"; }
        if i == 115 { return "Fujimoto"; }
        if i == 116 { return "Amamiya"; }
        if i == 117 { return "Chikafuji"; }
        if i == 118 { return "Ezakiya"; }
        if i == 119 { return "Fukuzawa"; }
        if i == 120 { return "Gushiken"; }
        if i == 121 { return "Hattori"; }
        if i == 122 { return "Ichimura"; }
        if i == 123 { return "Kagawa"; }
        if i == 124 { return "Kuroshima"; }
        if i == 125 { return "Matsubara"; }
        if i == 126 { return "Nishioka"; }
        if i == 127 { return "Oyamada"; }
        if i == 128 { return "Shirakawa"; }
        if i == 129 { return "Takeshita"; }
        if i == 130 { return "Umewaka"; }
        if i == 131 { return "Yanagida"; }
        if i == 132 { return "Aihara"; }
        if i == 133 { return "Ebisawa"; }
        if i == 134 { return "Funakoshi"; }
        if i == 135 { return "Hamasaki"; }
        if i == 136 { return "Iwatani"; }
        if i == 137 { return "Kajiwara"; }
        if i == 138 { return "Kusakabe"; }
        if i == 139 { return "Mizushima"; }
        if i == 140 { return "Nakazawa"; }
        if i == 141 { return "Okabayashi"; }
        if i == 142 { return "Sekiguchi"; }
        if i == 143 { return "Tsukamoto"; }
        if i == 144 { return "Uehara"; }
        if i == 145 { return "Yamanaka"; }
        if i == 146 { return "Aizawa"; }
        if i == 147 { return "Enomoto"; }
        if i == 148 { return "Furuhashi"; }
        if i == 149 { return "Higashiyama"; }
        return "Tanaka";
    }
}
