// Korean Names - 100 male, 100 female, 100 last names
public abstract class KdspKoreanNames {

    public static func GetMaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Min-jun"; }
        if i == 1 { return "Seo-jun"; }
        if i == 2 { return "Ji-hoon"; }
        if i == 3 { return "Jun-seo"; }
        if i == 4 { return "Hyun-woo"; }
        if i == 5 { return "Dong-hyun"; }
        if i == 6 { return "Sung-min"; }
        if i == 7 { return "Jae-won"; }
        if i == 8 { return "Tae-hyung"; }
        if i == 9 { return "Woo-jin"; }
        if i == 10 { return "Jin-woo"; }
        if i == 11 { return "Seung-ho"; }
        if i == 12 { return "Young-ho"; }
        if i == 13 { return "Sang-woo"; }
        if i == 14 { return "Joon-ho"; }
        if i == 15 { return "Ki-tae"; }
        if i == 16 { return "Chang-min"; }
        if i == 17 { return "Dae-jung"; }
        if i == 18 { return "Eun-woo"; }
        if i == 19 { return "Gun-woo"; }
        if i == 20 { return "Hak-joon"; }
        if i == 21 { return "In-sung"; }
        if i == 22 { return "Jung-hoon"; }
        if i == 23 { return "Kyung-ho"; }
        if i == 24 { return "Min-ho"; }
        if i == 25 { return "Nam-joon"; }
        if i == 26 { return "Pil-sung"; }
        if i == 27 { return "Rok-won"; }
        if i == 28 { return "Si-woo"; }
        if i == 29 { return "Tae-min"; }
        if i == 30 { return "Yong-jun"; }
        if i == 31 { return "Joon-young"; }
        if i == 32 { return "Byung-ho"; }
        if i == 33 { return "Chan-yeol"; }
        if i == 34 { return "Do-yun"; }
        if i == 35 { return "Ha-jun"; }
        if i == 36 { return "Il-sung"; }
        if i == 37 { return "Jong-min"; }
        if i == 38 { return "Kyu-hyun"; }
        if i == 39 { return "Myung-soo"; }
        if i == 40 { return "Rae-won"; }
        if i == 41 { return "Soo-hyun"; }
        if i == 42 { return "Ui-jin"; }
        if i == 43 { return "Won-bin"; }
        if i == 44 { return "Ye-jun"; }
        if i == 45 { return "Jae-hyun"; }
        if i == 46 { return "Bum-soo"; }
        if i == 47 { return "Chul-woo"; }
        if i == 48 { return "Dong-wook"; }
        if i == 49 { return "Han-sol"; }
        if i == 50 { return "Jae-sung"; }
        if i == 51 { return "Kang-min"; }
        if i == 52 { return "Min-su"; }
        if i == 53 { return "Seo-hyun"; }
        if i == 54 { return "Tae-won"; }
        if i == 55 { return "Yoo-jin"; }
        if i == 56 { return "Baek-hyun"; }
        if i == 57 { return "Cha-min"; }
        if i == 58 { return "Doo-joon"; }
        if i == 59 { return "Gi-kwang"; }
        if i == 60 { return "Ho-seok"; }
        if i == 61 { return "Jong-hyun"; }
        if i == 62 { return "Ki-bum"; }
        if i == 63 { return "Min-woo"; }
        if i == 64 { return "Seok-jin"; }
        if i == 65 { return "Tae-yang"; }
        if i == 66 { return "Yeon-jun"; }
        if i == 67 { return "Bo-gum"; }
        if i == 68 { return "Chan-ho"; }
        if i == 69 { return "Dong-min"; }
        if i == 70 { return "Gyu-ri"; }
        if i == 71 { return "Hyuk-jae"; }
        if i == 72 { return "Jong-kook"; }
        if i == 73 { return "Ki-hoon"; }
        if i == 74 { return "Min-gyu"; }
        if i == 75 { return "Se-hoon"; }
        if i == 76 { return "Tae-soo"; }
        if i == 77 { return "Won-ho"; }
        if i == 78 { return "Yu-jin"; }
        if i == 79 { return "Bin"; }
        if i == 80 { return "Chan"; }
        if i == 81 { return "Dae"; }
        if i == 82 { return "Gi"; }
        if i == 83 { return "Hwan"; }
        if i == 84 { return "Jang"; }
        if i == 85 { return "Kwon"; }
        if i == 86 { return "Man"; }
        if i == 87 { return "Seung"; }
        if i == 88 { return "Tae"; }
        if i == 89 { return "Woo"; }
        if i == 90 { return "Yong"; }
        if i == 91 { return "Jun"; }
        if i == 92 { return "Hoon"; }
        if i == 93 { return "Jin"; }
        if i == 94 { return "Ho"; }
        if i == 95 { return "Sung"; }
        if i == 96 { return "Won"; }
        if i == 97 { return "Young"; }
        if i == 98 { return "Soo"; }
        if i == 99 { return "Hyun"; }
        if i == 100 { return "Byung-Ho"; }
        if i == 101 { return "Chang-Min"; }
        if i == 102 { return "Dae-Sung"; }
        if i == 103 { return "Eun-Woo"; }
        if i == 104 { return "Gun-Woo"; }
        if i == 105 { return "Hyun-Woo"; }
        if i == 106 { return "In-Su"; }
        if i == 107 { return "Jae-Hyun"; }
        if i == 108 { return "Kang-Min"; }
        if i == 109 { return "Kwang-Su"; }
        if i == 110 { return "Min-Jun"; }
        if i == 111 { return "Nam-Il"; }
        if i == 112 { return "Sang-Hoon"; }
        if i == 113 { return "Tae-Yang"; }
        if i == 114 { return "Woo-Jin"; }
        if i == 115 { return "Yong-Su"; }
        if i == 116 { return "Chul-Soo"; }
        if i == 117 { return "Do-Hyun"; }
        if i == 118 { return "Gi-Hun"; }
        if i == 119 { return "Ho-Jin"; }
        if i == 120 { return "Il-Sung"; }
        if i == 121 { return "Jin-Woo"; }
        if i == 122 { return "Ki-Tae"; }
        if i == 123 { return "Man-Sik"; }
        if i == 124 { return "Nam-Gil"; }
        if i == 125 { return "Sang-Woo"; }
        if i == 126 { return "Tae-Min"; }
        if i == 127 { return "Won-Ho"; }
        if i == 128 { return "Young-Chul"; }
        if i == 129 { return "Byeong-Cheol"; }
        if i == 130 { return "Chan-Ho"; }
        if i == 131 { return "Dong-Hyun"; }
        if i == 132 { return "Geon-Woo"; }
        if i == 133 { return "Hae-Sung"; }
        if i == 134 { return "Ik-Jun"; }
        if i == 135 { return "Jung-Ho"; }
        if i == 136 { return "Kyung-Soo"; }
        if i == 137 { return "Min-Ho"; }
        if i == 138 { return "Oh-Sung"; }
        if i == 139 { return "Seok-Jin"; }
        if i == 140 { return "Tae-Joon"; }
        if i == 141 { return "Woo-Sik"; }
        if i == 142 { return "Yun-Ho"; }
        if i == 143 { return "Beom-Seok"; }
        if i == 144 { return "Chi-Won"; }
        if i == 145 { return "Doo-Joon"; }
        if i == 146 { return "Gwang-Hyun"; }
        if i == 147 { return "Hyun-Bin"; }
        if i == 148 { return "In-Guk"; }
        if i == 149 { return "Jae-Wook"; }
        return "Min-jun";
    }

    public static func GetFemaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Ji-yeon"; }
        if i == 1 { return "Soo-yeon"; }
        if i == 2 { return "Min-ji"; }
        if i == 3 { return "Ye-jin"; }
        if i == 4 { return "Hye-won"; }
        if i == 5 { return "Eun-ji"; }
        if i == 6 { return "Sung-hee"; }
        if i == 7 { return "Yoo-na"; }
        if i == 8 { return "Ha-na"; }
        if i == 9 { return "Mi-young"; }
        if i == 10 { return "Sun-hee"; }
        if i == 11 { return "Seo-yeon"; }
        if i == 12 { return "Bo-ram"; }
        if i == 13 { return "Chae-won"; }
        if i == 14 { return "Da-hye"; }
        if i == 15 { return "Ga-eun"; }
        if i == 16 { return "Hye-jin"; }
        if i == 17 { return "In-young"; }
        if i == 18 { return "Ji-won"; }
        if i == 19 { return "Kyung-mi"; }
        if i == 20 { return "Mi-na"; }
        if i == 21 { return "Na-young"; }
        if i == 22 { return "Ok-hee"; }
        if i == 23 { return "Seung-yeon"; }
        if i == 24 { return "Yeon-hee"; }
        if i == 25 { return "Ji-soo"; }
        if i == 26 { return "Ae-rin"; }
        if i == 27 { return "Bo-young"; }
        if i == 28 { return "Cho-hee"; }
        if i == 29 { return "Da-som"; }
        if i == 30 { return "Eun-bi"; }
        if i == 31 { return "Ha-eun"; }
        if i == 32 { return "Hyo-jin"; }
        if i == 33 { return "Ji-hye"; }
        if i == 34 { return "Kyu-ri"; }
        if i == 35 { return "Mi-sun"; }
        if i == 36 { return "Na-ri"; }
        if i == 37 { return "Se-ra"; }
        if i == 38 { return "Yoo-ri"; }
        if i == 39 { return "Ji-min"; }
        if i == 40 { return "Ah-reum"; }
        if i == 41 { return "Bo-mi"; }
        if i == 42 { return "Chae-rin"; }
        if i == 43 { return "Da-in"; }
        if i == 44 { return "Eun-hye"; }
        if i == 45 { return "Ha-yoon"; }
        if i == 46 { return "Hye-rim"; }
        if i == 47 { return "Ji-eun"; }
        if i == 48 { return "Mi-hee"; }
        if i == 49 { return "Na-eun"; }
        if i == 50 { return "So-yeon"; }
        if i == 51 { return "Yeon-ji"; }
        if i == 52 { return "Ji-a"; }
        if i == 53 { return "Ae-young"; }
        if i == 54 { return "Bo-na"; }
        if i == 55 { return "Cho-rong"; }
        if i == 56 { return "Da-yeon"; }
        if i == 57 { return "Eun-seo"; }
        if i == 58 { return "Ha-rin"; }
        if i == 59 { return "Hye-sun"; }
        if i == 60 { return "Ji-hyun"; }
        if i == 61 { return "Mi-kyung"; }
        if i == 62 { return "Na-hee"; }
        if i == 63 { return "So-jin"; }
        if i == 64 { return "Yeon-woo"; }
        if i == 65 { return "Jin-ah"; }
        if i == 66 { return "Ara"; }
        if i == 67 { return "Bo-bae"; }
        if i == 68 { return "Chae-yeon"; }
        if i == 69 { return "Da-mi"; }
        if i == 70 { return "Eun-young"; }
        if i == 71 { return "Ha-jung"; }
        if i == 72 { return "Hyo-rin"; }
        if i == 73 { return "Ji-na"; }
        if i == 74 { return "Mi-ran"; }
        if i == 75 { return "Na-yeon"; }
        if i == 76 { return "So-hee"; }
        if i == 77 { return "Ye-na"; }
        if i == 78 { return "Jin-hee"; }
        if i == 79 { return "Bi"; }
        if i == 80 { return "Bo"; }
        if i == 81 { return "Cho"; }
        if i == 82 { return "Da"; }
        if i == 83 { return "Eun"; }
        if i == 84 { return "Ha"; }
        if i == 85 { return "Hye"; }
        if i == 86 { return "Ji"; }
        if i == 87 { return "Mi"; }
        if i == 88 { return "Na"; }
        if i == 89 { return "Seo"; }
        if i == 90 { return "Yeon"; }
        if i == 91 { return "Su"; }
        if i == 92 { return "Hee"; }
        if i == 93 { return "Young"; }
        if i == 94 { return "Won"; }
        if i == 95 { return "Ri"; }
        if i == 96 { return "Min"; }
        if i == 97 { return "Ye"; }
        if i == 98 { return "Ga"; }
        if i == 99 { return "So"; }
        if i == 100 { return "Bo-Ra"; }
        if i == 101 { return "Chae-Won"; }
        if i == 102 { return "Da-Eun"; }
        if i == 103 { return "Eun-Ji"; }
        if i == 104 { return "Ga-Young"; }
        if i == 105 { return "Ha-Eun"; }
        if i == 106 { return "In-Na"; }
        if i == 107 { return "Ji-Woo"; }
        if i == 108 { return "Kyung-Mi"; }
        if i == 109 { return "Mi-Rae"; }
        if i == 110 { return "Na-Yeon"; }
        if i == 111 { return "Sang-Mi"; }
        if i == 112 { return "Tae-Hee"; }
        if i == 113 { return "Woo-Ri"; }
        if i == 114 { return "Ye-Jin"; }
        if i == 115 { return "Ah-Reum"; }
        if i == 116 { return "Bo-Young"; }
        if i == 117 { return "Chun-Hei"; }
        if i == 118 { return "Da-Som"; }
        if i == 119 { return "Eun-Kyung"; }
        if i == 120 { return "Gyu-Ri"; }
        if i == 121 { return "Hae-Won"; }
        if i == 122 { return "Il-Hwa"; }
        if i == 123 { return "Ji-Yeon"; }
        if i == 124 { return "Kyung-Ja"; }
        if i == 125 { return "Mi-Sook"; }
        if i == 126 { return "Nam-Joo"; }
        if i == 127 { return "Se-Yeon"; }
        if i == 128 { return "Ha-Neul"; }
        if i == 129 { return "Yeo-Reum"; }
        if i == 130 { return "Byul"; }
        if i == 131 { return "Chae-Rin"; }
        if i == 132 { return "Dal-Rae"; }
        if i == 133 { return "Eun-Bi"; }
        if i == 134 { return "Ga-In"; }
        if i == 135 { return "Hana"; }
        if i == 136 { return "In-Young"; }
        if i == 137 { return "Jin-Ah"; }
        if i == 138 { return "Kyung-Hee"; }
        if i == 139 { return "Mi-Cha"; }
        if i == 140 { return "Nari"; }
        if i == 141 { return "Seo-Yeon"; }
        if i == 142 { return "Ye-Won"; }
        if i == 143 { return "A-Yeong"; }
        if i == 144 { return "Bom"; }
        if i == 145 { return "Cho-Hee"; }
        if i == 146 { return "Da-Hye"; }
        if i == 147 { return "Eun-Seo"; }
        if i == 148 { return "Go-Eun"; }
        if i == 149 { return "Hye-Jin"; }
        return "Ji-yeon";
    }

    public static func GetLastName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 135);
        if i == 0 { return "Kim"; }
        if i == 1 { return "Lee"; }
        if i == 2 { return "Park"; }
        if i == 3 { return "Choi"; }
        if i == 4 { return "Jung"; }
        if i == 5 { return "Kang"; }
        if i == 6 { return "Cho"; }
        if i == 7 { return "Yoon"; }
        if i == 8 { return "Jang"; }
        if i == 9 { return "Lim"; }
        if i == 10 { return "Han"; }
        if i == 11 { return "Oh"; }
        if i == 12 { return "Seo"; }
        if i == 13 { return "Shin"; }
        if i == 14 { return "Kwon"; }
        if i == 15 { return "Hwang"; }
        if i == 16 { return "Ahn"; }
        if i == 17 { return "Song"; }
        if i == 18 { return "Jeon"; }
        if i == 19 { return "Hong"; }
        if i == 20 { return "Yu"; }
        if i == 21 { return "Go"; }
        if i == 22 { return "Moon"; }
        if i == 23 { return "Yang"; }
        if i == 24 { return "Son"; }
        if i == 25 { return "Bae"; }
        if i == 26 { return "Baek"; }
        if i == 27 { return "Heo"; }
        if i == 28 { return "Nam"; }
        if i == 29 { return "Sim"; }
        if i == 30 { return "Noh"; }
        if i == 31 { return "Ha"; }
        if i == 32 { return "Kwak"; }
        if i == 33 { return "Sung"; }
        if i == 34 { return "Cha"; }
        if i == 35 { return "Jo"; }
        if i == 36 { return "Byun"; }
        if i == 37 { return "Woo"; }
        if i == 38 { return "Min"; }
        if i == 39 { return "Yoo"; }
        if i == 40 { return "Ji"; }
        if i == 41 { return "Ryu"; }
        if i == 42 { return "Won"; }
        if i == 43 { return "Chung"; }
        if i == 44 { return "In"; }
        if i == 45 { return "Bang"; }
        if i == 46 { return "Wang"; }
        if i == 47 { return "Yeo"; }
        if i == 48 { return "Ku"; }
        if i == 49 { return "Do"; }
        if i == 50 { return "Ma"; }
        if i == 51 { return "Bo"; }
        if i == 52 { return "Myung"; }
        if i == 53 { return "Gi"; }
        if i == 54 { return "Dong"; }
        if i == 55 { return "Seol"; }
        if i == 56 { return "Pyo"; }
        if i == 57 { return "Sa"; }
        if i == 58 { return "Gong"; }
        if i == 59 { return "Tak"; }
        if i == 60 { return "Jin"; }
        if i == 61 { return "Pi"; }
        if i == 62 { return "Eom"; }
        if i == 63 { return "Seong"; }
        if i == 64 { return "Geum"; }
        if i == 65 { return "Gyeong"; }
        if i == 66 { return "Cheong"; }
        if i == 67 { return "Bong"; }
        if i == 68 { return "Hyun"; }
        if i == 69 { return "Mun"; }
        if i == 70 { return "Chu"; }
        if i == 71 { return "Pang"; }
        if i == 72 { return "Wi"; }
        if i == 73 { return "Gan"; }
        if i == 74 { return "Guk"; }
        if i == 75 { return "Ja"; }
        if i == 76 { return "Jeung"; }
        if i == 77 { return "Yim"; }
        if i == 78 { return "Pan"; }
        if i == 79 { return "Su"; }
        if i == 80 { return "Ok"; }
        if i == 81 { return "Tae"; }
        if i == 82 { return "Po"; }
        if i == 83 { return "Cheon"; }
        if i == 84 { return "Ban"; }
        if i == 85 { return "Seung"; }
        if i == 86 { return "Um"; }
        if i == 87 { return "Ra"; }
        if i == 88 { return "Si"; }
        if i == 89 { return "Maeng"; }
        if i == 90 { return "Yuk"; }
        if i == 91 { return "Chin"; }
        if i == 92 { return "Da"; }
        if i == 93 { return "Bi"; }
        if i == 94 { return "Jwa"; }
        if i == 95 { return "Ye"; }
        if i == 96 { return "Bok"; }
        if i == 97 { return "Gwak"; }
        if i == 98 { return "Hu"; }
        if i == 99 { return "Jae"; }
        if i == 100 { return "Gil"; }
        if i == 101 { return "Im"; }
        if i == 102 { return "Ko"; }
        if i == 103 { return "Uhm"; }
        if i == 104 { return "Chae"; }
        if i == 105 { return "Doh"; }
        if i == 106 { return "Koo"; }
        if i == 107 { return "Yeon"; }
        if i == 108 { return "Gu"; }
        if i == 109 { return "Ohm"; }
        if i == 110 { return "Rha"; }
        if i == 111 { return "Byeon"; }
        if i == 112 { return "Dokgo"; }
        if i == 113 { return "Eun"; }
        if i == 114 { return "Gam"; }
        if i == 115 { return "Hwangbo"; }
        if i == 116 { return "Jegal"; }
        if i == 117 { return "Kal"; }
        if i == 118 { return "Namgung"; }
        if i == 119 { return "Ogeum"; }
        if i == 120 { return "Pyeon"; }
        if i == 121 { return "Sagong"; }
        if i == 122 { return "Seonu"; }
        if i == 123 { return "Tan"; }
        if i == 124 { return "Yeom"; }
        if i == 125 { return "Deok"; }
        if i == 126 { return "Gae"; }
        if i == 127 { return "Hyeon"; }
        if i == 128 { return "Kang-Jeon"; }
        if i == 129 { return "Mo"; }
        if i == 130 { return "No"; }
        if i == 131 { return "On"; }
        if i == 132 { return "Pung"; }
        if i == 133 { return "Sang"; }
        if i == 134 { return "Tang"; }
        return "Kim";
    }
}
