// Slavic Names - 100 male, 100 female, 100 last names
public abstract class KdspSlavicNames {

    public static func GetMaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 148);
        if i == 0 { return "Viktor"; }
        if i == 1 { return "Dmitri"; }
        if i == 2 { return "Alexei"; }
        if i == 3 { return "Sergei"; }
        if i == 4 { return "Nikolai"; }
        if i == 5 { return "Ivan"; }
        if i == 6 { return "Andrei"; }
        if i == 7 { return "Mikhail"; }
        if i == 8 { return "Pavel"; }
        if i == 9 { return "Boris"; }
        if i == 10 { return "Yuri"; }
        if i == 11 { return "Oleg"; }
        if i == 12 { return "Vasily"; }
        if i == 13 { return "Grigori"; }
        if i == 14 { return "Maxim"; }
        if i == 15 { return "Roman"; }
        if i == 16 { return "Stanislav"; }
        if i == 17 { return "Vladislav"; }
        if i == 18 { return "Anatoly"; }
        if i == 19 { return "Evgeni"; }
        if i == 20 { return "Konstantin"; }
        if i == 21 { return "Leonid"; }
        if i == 22 { return "Pyotr"; }
        if i == 23 { return "Valery"; }
        if i == 24 { return "Vitaly"; }
        if i == 25 { return "Igor"; }
        if i == 26 { return "Arkady"; }
        if i == 27 { return "Denis"; }
        if i == 28 { return "Gleb"; }
        if i == 29 { return "Kirill"; }
        if i == 30 { return "Matvei"; }
        if i == 31 { return "Nikita"; }
        if i == 32 { return "Ruslan"; }
        if i == 33 { return "Timofei"; }
        if i == 34 { return "Yaroslav"; }
        if i == 35 { return "Bogdan"; }
        if i == 36 { return "Danil"; }
        if i == 37 { return "Fedor"; }
        if i == 38 { return "Ilya"; }
        if i == 39 { return "Lev"; }
        if i == 40 { return "Marek"; }
        if i == 41 { return "Radek"; }
        if i == 42 { return "Stepan"; }
        if i == 43 { return "Vadim"; }
        if i == 44 { return "Yegor"; }
        if i == 45 { return "Artem"; }
        if i == 46 { return "Czech"; }
        if i == 47 { return "Emil"; }
        if i == 48 { return "Goran"; }
        if i == 49 { return "Jan"; }
        if i == 50 { return "Kazimir"; }
        if i == 51 { return "Luka"; }
        if i == 52 { return "Milan"; }
        if i == 53 { return "Oskar"; }
        if i == 54 { return "Pawel"; }
        if i == 55 { return "Radoslav"; }
        if i == 56 { return "Slawomir"; }
        if i == 57 { return "Tomasz"; }
        if i == 58 { return "Waclaw"; }
        if i == 59 { return "Zbigniew"; }
        if i == 60 { return "Antoni"; }
        if i == 61 { return "Bronislaw"; }
        if i == 62 { return "Czeslaw"; }
        if i == 63 { return "Dariusz"; }
        if i == 64 { return "Filip"; }
        if i == 65 { return "Henryk"; }
        if i == 66 { return "Jakub"; }
        if i == 67 { return "Krzysztof"; }
        if i == 68 { return "Lukasz"; }
        if i == 69 { return "Miroslaw"; }
        if i == 70 { return "Piotr"; }
        if i == 71 { return "Rafal"; }
        if i == 72 { return "Stefan"; }
        if i == 73 { return "Tadeusz"; }
        if i == 74 { return "Wojciech"; }
        if i == 75 { return "Zygmunt"; }
        if i == 76 { return "Adam"; }
        if i == 77 { return "Bohdan"; }
        if i == 78 { return "Dragomir"; }
        if i == 79 { return "Grzegorz"; }
        if i == 80 { return "Janusz"; }
        if i == 81 { return "Kazik"; }
        if i == 82 { return "Leszek"; }
        if i == 83 { return "Maciej"; }
        if i == 84 { return "Norbert"; }
        if i == 85 { return "Przemek"; }
        if i == 86 { return "Ryszard"; }
        if i == 87 { return "Szymon"; }
        if i == 88 { return "Teodor"; }
        if i == 89 { return "Wiktor"; }
        if i == 90 { return "Zenon"; }
        if i == 91 { return "Aleksander"; }
        if i == 92 { return "Bartosz"; }
        if i == 93 { return "Damian"; }
        if i == 94 { return "Edmund"; }
        if i == 95 { return "Feliks"; }
        if i == 96 { return "Hubert"; }
        if i == 97 { return "Jacek"; }
        if i == 98 { return "Karol"; }
        if i == 99 { return "Marcin"; }
        if i == 100 { return "Aleksandr"; }
        if i == 101 { return "Casimir"; }
        if i == 102 { return "Fyodor"; }
        if i == 103 { return "Gennady"; }
        if i == 104 { return "Havel"; }
        if i == 105 { return "Jaroslav"; }
        if i == 106 { return "Milos"; }
        if i == 107 { return "Timofey"; }
        if i == 108 { return "Ulyan"; }
        if i == 109 { return "Dusan"; }
        if i == 110 { return "Miroslav"; }
        if i == 111 { return "Ondrej"; }
        if i == 112 { return "Rostislav"; }
        if i == 113 { return "Svyatoslav"; }
        if i == 114 { return "Vaclav"; }
        if i == 115 { return "Wladyslaw"; }
        if i == 116 { return "Yevgeny"; }
        if i == 117 { return "Zdenek"; }
        if i == 118 { return "Dobromir"; }
        if i == 119 { return "Vsevolod"; }
        if i == 120 { return "Mstislav"; }
        if i == 121 { return "Ratibor"; }
        if i == 122 { return "Sviatopolk"; }
        if i == 123 { return "Dobroslav"; }
        if i == 124 { return "Ludomir"; }
        if i == 125 { return "Przemyslaw"; }
        if i == 126 { return "Wieslaw"; }
        if i == 127 { return "Zbyszek"; }
        if i == 128 { return "Bohumil"; }
        if i == 129 { return "Ctibor"; }
        if i == 130 { return "Drahomir"; }
        if i == 131 { return "Jaromir"; }
        if i == 132 { return "Kazimierz"; }
        if i == 133 { return "Lubomir"; }
        if i == 134 { return "Mieczyslaw"; }
        if i == 135 { return "Nikifor"; }
        if i == 136 { return "Oldrich"; }
        if i == 137 { return "Premysl"; }
        if i == 138 { return "Tichomir"; }
        if i == 139 { return "Velimir"; }
        if i == 140 { return "Wladimir"; }
        if i == 141 { return "Zelimir"; }
        if i == 142 { return "Bozidar"; }
        if i == 143 { return "Chvalimir"; }
        if i == 144 { return "Dalibor"; }
        if i == 145 { return "Gniewomir"; }
        if i == 146 { return "Krzesimir"; }
        if i == 147 { return "Milivoj"; }
        return "Viktor";
    }

    public static func GetFemaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 146);
        if i == 0 { return "Natasha"; }
        if i == 1 { return "Tatiana"; }
        if i == 2 { return "Olga"; }
        if i == 3 { return "Svetlana"; }
        if i == 4 { return "Irina"; }
        if i == 5 { return "Elena"; }
        if i == 6 { return "Anna"; }
        if i == 7 { return "Yulia"; }
        if i == 8 { return "Maria"; }
        if i == 9 { return "Katya"; }
        if i == 10 { return "Anastasia"; }
        if i == 11 { return "Ekaterina"; }
        if i == 12 { return "Oksana"; }
        if i == 13 { return "Larisa"; }
        if i == 14 { return "Galina"; }
        if i == 15 { return "Valentina"; }
        if i == 16 { return "Lyudmila"; }
        if i == 17 { return "Marina"; }
        if i == 18 { return "Vera"; }
        if i == 19 { return "Nadia"; }
        if i == 20 { return "Daria"; }
        if i == 21 { return "Sofia"; }
        if i == 22 { return "Alina"; }
        if i == 23 { return "Polina"; }
        if i == 24 { return "Yelena"; }
        if i == 25 { return "Anya"; }
        if i == 26 { return "Kira"; }
        if i == 27 { return "Lena"; }
        if i == 28 { return "Mila"; }
        if i == 29 { return "Nina"; }
        if i == 30 { return "Raya"; }
        if i == 31 { return "Sasha"; }
        if i == 32 { return "Tamara"; }
        if i == 33 { return "Veronika"; }
        if i == 34 { return "Zoya"; }
        if i == 35 { return "Agnieszka"; }
        if i == 36 { return "Barbara"; }
        if i == 37 { return "Celina"; }
        if i == 38 { return "Dorota"; }
        if i == 39 { return "Ewa"; }
        if i == 40 { return "Grazyna"; }
        if i == 41 { return "Halina"; }
        if i == 42 { return "Iwona"; }
        if i == 43 { return "Jadwiga"; }
        if i == 44 { return "Krystyna"; }
        if i == 45 { return "Lucyna"; }
        if i == 46 { return "Magda"; }
        if i == 47 { return "Natalia"; }
        if i == 48 { return "Patrycja"; }
        if i == 49 { return "Renata"; }
        if i == 50 { return "Sylwia"; }
        if i == 51 { return "Teresa"; }
        if i == 52 { return "Urszula"; }
        if i == 53 { return "Wanda"; }
        if i == 54 { return "Zofia"; }
        if i == 55 { return "Aleksandra"; }
        if i == 56 { return "Beata"; }
        if i == 57 { return "Danuta"; }
        if i == 58 { return "Edyta"; }
        if i == 59 { return "Franciszka"; }
        if i == 60 { return "Gabriela"; }
        if i == 61 { return "Helena"; }
        if i == 62 { return "Izabela"; }
        if i == 63 { return "Joanna"; }
        if i == 64 { return "Katarzyna"; }
        if i == 65 { return "Lidia"; }
        if i == 66 { return "Malgorzata"; }
        if i == 67 { return "Ola"; }
        if i == 68 { return "Paulina"; }
        if i == 69 { return "Romana"; }
        if i == 70 { return "Stanislawa"; }
        if i == 71 { return "Tatjana"; }
        if i == 72 { return "Victoria"; }
        if i == 73 { return "Wieslawa"; }
        if i == 74 { return "Zuzanna"; }
        if i == 75 { return "Ada"; }
        if i == 76 { return "Bozena"; }
        if i == 77 { return "Czeslawa"; }
        if i == 78 { return "Diana"; }
        if i == 79 { return "Emilia"; }
        if i == 80 { return "Felicja"; }
        if i == 81 { return "Genowefa"; }
        if i == 82 { return "Hanna"; }
        if i == 83 { return "Irena"; }
        if i == 84 { return "Julia"; }
        if i == 85 { return "Karolina"; }
        if i == 86 { return "Laura"; }
        if i == 87 { return "Monika"; }
        if i == 88 { return "Otylia"; }
        if i == 89 { return "Petra"; }
        if i == 90 { return "Regina"; }
        if i == 91 { return "Sandra"; }
        if i == 92 { return "Tina"; }
        if i == 93 { return "Violetta"; }
        if i == 94 { return "Weronika"; }
        if i == 95 { return "Ksenia"; }
        if i == 96 { return "Alyona"; }
        if i == 97 { return "Bogumila"; }
        if i == 98 { return "Dagmara"; }
        if i == 99 { return "Elzbieta"; }
        if i == 100 { return "Ceslava"; }
        if i == 101 { return "Faina"; }
        if i == 102 { return "Ludmila"; }
        if i == 103 { return "Raisa"; }
        if i == 104 { return "Uliana"; }
        if i == 105 { return "Vasilisa"; }
        if i == 106 { return "Bogdana"; }
        if i == 107 { return "Darya"; }
        if i == 108 { return "Feodora"; }
        if i == 109 { return "Inessa"; }
        if i == 110 { return "Jolanta"; }
        if i == 111 { return "Milena"; }
        if i == 112 { return "Natalya"; }
        if i == 113 { return "Praskovya"; }
        if i == 114 { return "Stanislava"; }
        if i == 115 { return "Zlata"; }
        if i == 116 { return "Bronislava"; }
        if i == 117 { return "Dominika"; }
        if i == 118 { return "Evgenia"; }
        if i == 119 { return "Halyna"; }
        if i == 120 { return "Wioletta"; }
        if i == 121 { return "Dobrawa"; }
        if i == 122 { return "Eufemia"; }
        if i == 123 { return "Grzymislawa"; }
        if i == 124 { return "Jaroslava"; }
        if i == 125 { return "Kazimiera"; }
        if i == 126 { return "Ludmilla"; }
        if i == 127 { return "Mieczyslawa"; }
        if i == 128 { return "Nikola"; }
        if i == 129 { return "Przemyslawa"; }
        if i == 130 { return "Radmila"; }
        if i == 131 { return "Slavena"; }
        if i == 132 { return "Tekla"; }
        if i == 133 { return "Vlasta"; }
        if i == 134 { return "Wladyslawa"; }
        if i == 135 { return "Zdenka"; }
        if i == 136 { return "Bozhena"; }
        if i == 137 { return "Miloslava"; }
        if i == 138 { return "Drahoslava"; }
        if i == 139 { return "Kvetoslava"; }
        if i == 140 { return "Libuse"; }
        if i == 141 { return "Ruzena"; }
        if i == 142 { return "Stanimira"; }
        if i == 143 { return "Vratislava"; }
        if i == 144 { return "Zora"; }
        if i == 145 { return "Zivka"; }
        return "Natasha";
    }

    public static func GetLastName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Volkov"; }
        if i == 1 { return "Ivanov"; }
        if i == 2 { return "Petrov"; }
        if i == 3 { return "Kozlov"; }
        if i == 4 { return "Sokolov"; }
        if i == 5 { return "Popov"; }
        if i == 6 { return "Morozov"; }
        if i == 7 { return "Novikov"; }
        if i == 8 { return "Kuznetsov"; }
        if i == 9 { return "Lebedev"; }
        if i == 10 { return "Smirnov"; }
        if i == 11 { return "Fedorov"; }
        if i == 12 { return "Orlov"; }
        if i == 13 { return "Mikhailov"; }
        if i == 14 { return "Pavlov"; }
        if i == 15 { return "Egorov"; }
        if i == 16 { return "Vasiliev"; }
        if i == 17 { return "Zaitsev"; }
        if i == 18 { return "Stepanov"; }
        if i == 19 { return "Alexandrov"; }
        if i == 20 { return "Kowalski"; }
        if i == 21 { return "Nowak"; }
        if i == 22 { return "Wisniewski"; }
        if i == 23 { return "Wojciechowski"; }
        if i == 24 { return "Kowalczyk"; }
        if i == 25 { return "Kaminski"; }
        if i == 26 { return "Lewandowski"; }
        if i == 27 { return "Zielinski"; }
        if i == 28 { return "Szymanski"; }
        if i == 29 { return "Wozniak"; }
        if i == 30 { return "Dabrowski"; }
        if i == 31 { return "Kozlowski"; }
        if i == 32 { return "Jankowski"; }
        if i == 33 { return "Mazur"; }
        if i == 34 { return "Kwiatkowski"; }
        if i == 35 { return "Krawczyk"; }
        if i == 36 { return "Piotrowski"; }
        if i == 37 { return "Grabowski"; }
        if i == 38 { return "Nowakowski"; }
        if i == 39 { return "Pawlak"; }
        if i == 40 { return "Michalski"; }
        if i == 41 { return "Adamczyk"; }
        if i == 42 { return "Dudek"; }
        if i == 43 { return "Zajac"; }
        if i == 44 { return "Wieczorek"; }
        if i == 45 { return "Jablonski"; }
        if i == 46 { return "Krol"; }
        if i == 47 { return "Majewski"; }
        if i == 48 { return "Olszewski"; }
        if i == 49 { return "Jaworski"; }
        if i == 50 { return "Malinowski"; }
        if i == 51 { return "Stępień"; }
        if i == 52 { return "Gorski"; }
        if i == 53 { return "Rutkowski"; }
        if i == 54 { return "Ostrowski"; }
        if i == 55 { return "Tomaszewski"; }
        if i == 56 { return "Pietrzak"; }
        if i == 57 { return "Marciniak"; }
        if i == 58 { return "Wrobel"; }
        if i == 59 { return "Zalewski"; }
        if i == 60 { return "Jakubowski"; }
        if i == 61 { return "Jasinski"; }
        if i == 62 { return "Zawadzki"; }
        if i == 63 { return "Sadowski"; }
        if i == 64 { return "Bak"; }
        if i == 65 { return "Chmielewski"; }
        if i == 66 { return "Wlodarczyk"; }
        if i == 67 { return "Borkowski"; }
        if i == 68 { return "Czarnecki"; }
        if i == 69 { return "Sawicki"; }
        if i == 70 { return "Sokolowski"; }
        if i == 71 { return "Maciejewski"; }
        if i == 72 { return "Szczepanski"; }
        if i == 73 { return "Kucharski"; }
        if i == 74 { return "Kalinowski"; }
        if i == 75 { return "Wysocki"; }
        if i == 76 { return "Adamski"; }
        if i == 77 { return "Sobczak"; }
        if i == 78 { return "Czerwinski"; }
        if i == 79 { return "Glowacki"; }
        if i == 80 { return "Sikorski"; }
        if i == 81 { return "Kaczmarek"; }
        if i == 82 { return "Wasilewski"; }
        if i == 83 { return "Kubiak"; }
        if i == 84 { return "Ciesla"; }
        if i == 85 { return "Mazurek"; }
        if i == 86 { return "Kolodziej"; }
        if i == 87 { return "Kazmierczak"; }
        if i == 88 { return "Sobczyk"; }
        if i == 89 { return "Konieczny"; }
        if i == 90 { return "Blaszczyk"; }
        if i == 91 { return "Zakrzewski"; }
        if i == 92 { return "Gorecki"; }
        if i == 93 { return "Wozniacki"; }
        if i == 94 { return "Przybylski"; }
        if i == 95 { return "Polak"; }
        if i == 96 { return "Krupa"; }
        if i == 97 { return "Leszczynski"; }
        if i == 98 { return "Wroblewski"; }
        if i == 99 { return "Urbaniak"; }
        if i == 100 { return "Antonov"; }
        if i == 101 { return "Bielski"; }
        if i == 102 { return "Dombrowski"; }
        if i == 103 { return "Golubev"; }
        if i == 104 { return "Horvat"; }
        if i == 105 { return "Ivanenko"; }
        if i == 106 { return "Nowicki"; }
        if i == 107 { return "Pavlenko"; }
        if i == 108 { return "Romanov"; }
        if i == 109 { return "Tkachenko"; }
        if i == 110 { return "Ulanov"; }
        if i == 111 { return "Yakovlev"; }
        if i == 112 { return "Andreyev"; }
        if i == 113 { return "Bondarenko"; }
        if i == 114 { return "Chernov"; }
        if i == 115 { return "Filipov"; }
        if i == 116 { return "Hrabal"; }
        if i == 117 { return "Ilyin"; }
        if i == 118 { return "Jelinek"; }
        if i == 119 { return "Kovac"; }
        if i == 120 { return "Lisowski"; }
        if i == 121 { return "Medvedev"; }
        if i == 122 { return "Novak"; }
        if i == 123 { return "Rybak"; }
        if i == 124 { return "Titov"; }
        if i == 125 { return "Urban"; }
        if i == 126 { return "Wojcik"; }
        if i == 127 { return "Belov"; }
        if i == 128 { return "Cerny"; }
        if i == 129 { return "Dvorak"; }
        if i == 130 { return "Frolov"; }
        if i == 131 { return "Gavrilov"; }
        if i == 132 { return "Vishnevsky"; }
        if i == 133 { return "Baranowski"; }
        if i == 134 { return "Dzhugashvili"; }
        if i == 135 { return "Fedoseev"; }
        if i == 136 { return "Hlinka"; }
        if i == 137 { return "Ignatiev"; }
        if i == 138 { return "Makarenko"; }
        if i == 139 { return "Nemcova"; }
        if i == 140 { return "Okhotnik"; }
        if i == 141 { return "Pilsudski"; }
        if i == 142 { return "Ruzicka"; }
        if i == 143 { return "Tarasenko"; }
        if i == 144 { return "Udovenko"; }
        if i == 145 { return "Vondracek"; }
        if i == 146 { return "Wawrzyniak"; }
        if i == 147 { return "Yaroshenko"; }
        if i == 148 { return "Zborowski"; }
        if i == 149 { return "Bartosz"; }
        return "Volkov";
    }
}
