// Southeast Asian Names - 100 male, 100 female, 100 last names
public abstract class KdspSoutheastAsianNames {

    public static func GetMaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 148);
        if i == 0 { return "Nguyen"; }
        if i == 1 { return "Tran"; }
        if i == 2 { return "Minh"; }
        if i == 3 { return "Duc"; }
        if i == 4 { return "Hai"; }
        if i == 5 { return "Long"; }
        if i == 6 { return "Hung"; }
        if i == 7 { return "Phong"; }
        if i == 8 { return "Khanh"; }
        if i == 9 { return "Thai"; }
        if i == 10 { return "Arjun"; }
        if i == 11 { return "Bao"; }
        if i == 12 { return "Cuong"; }
        if i == 13 { return "Duy"; }
        if i == 14 { return "Hieu"; }
        if i == 15 { return "Khoa"; }
        if i == 16 { return "Loc"; }
        if i == 17 { return "Nam"; }
        if i == 18 { return "Quang"; }
        if i == 19 { return "Son"; }
        if i == 20 { return "Tan"; }
        if i == 21 { return "Vinh"; }
        if i == 22 { return "Somchai"; }
        if i == 23 { return "Prasert"; }
        if i == 24 { return "Somsak"; }
        if i == 25 { return "Narong"; }
        if i == 26 { return "Sombat"; }
        if i == 27 { return "Pichai"; }
        if i == 28 { return "Anand"; }
        if i == 29 { return "Boon"; }
        if i == 30 { return "Chai"; }
        if i == 31 { return "Det"; }
        if i == 32 { return "Ek"; }
        if i == 33 { return "Fa"; }
        if i == 34 { return "Gan"; }
        if i == 35 { return "Heng"; }
        if i == 36 { return "Isra"; }
        if i == 37 { return "Jet"; }
        if i == 38 { return "Kiet"; }
        if i == 39 { return "Lek"; }
        if i == 40 { return "Manu"; }
        if i == 41 { return "Niran"; }
        if i == 42 { return "Ong"; }
        if i == 43 { return "Phan"; }
        if i == 44 { return "Quan"; }
        if i == 45 { return "Rith"; }
        if i == 46 { return "Sak"; }
        if i == 47 { return "Tuan"; }
        if i == 48 { return "Udom"; }
        if i == 49 { return "Viet"; }
        if i == 50 { return "Win"; }
        if i == 51 { return "Xuan"; }
        if i == 52 { return "Yut"; }
        if i == 53 { return "Zaw"; }
        if i == 54 { return "Ahmad"; }
        if i == 55 { return "Bayu"; }
        if i == 56 { return "Dewa"; }
        if i == 57 { return "Eko"; }
        if i == 58 { return "Fajar"; }
        if i == 59 { return "Guntur"; }
        if i == 60 { return "Hadi"; }
        if i == 61 { return "Irfan"; }
        if i == 62 { return "Joko"; }
        if i == 63 { return "Kurnia"; }
        if i == 64 { return "Lutfi"; }
        if i == 65 { return "Miftah"; }
        if i == 66 { return "Nugroho"; }
        if i == 67 { return "Putra"; }
        if i == 68 { return "Rizal"; }
        if i == 69 { return "Surya"; }
        if i == 70 { return "Teguh"; }
        if i == 71 { return "Wahyu"; }
        if i == 72 { return "Yusuf"; }
        if i == 73 { return "Zainal"; }
        if i == 74 { return "Agus"; }
        if i == 75 { return "Budi"; }
        if i == 76 { return "Dedi"; }
        if i == 77 { return "Feri"; }
        if i == 78 { return "Gilang"; }
        if i == 79 { return "Hendri"; }
        if i == 80 { return "Indra"; }
        if i == 81 { return "Jaya"; }
        if i == 82 { return "Krisna"; }
        if i == 83 { return "Lukman"; }
        if i == 84 { return "Made"; }
        if i == 85 { return "Nyoman"; }
        if i == 86 { return "Pandu"; }
        if i == 87 { return "Rahmat"; }
        if i == 88 { return "Setya"; }
        if i == 89 { return "Tri"; }
        if i == 90 { return "Umar"; }
        if i == 91 { return "Wawan"; }
        if i == 92 { return "Yudi"; }
        if i == 93 { return "Zaki"; }
        if i == 94 { return "Ardi"; }
        if i == 95 { return "Bambang"; }
        if i == 96 { return "Cahya"; }
        if i == 97 { return "Dani"; }
        if i == 98 { return "Ferry"; }
        if i == 99 { return "Gede"; }
        if i == 100 { return "Arif"; }
        if i == 101 { return "Dinh"; }
        if i == 102 { return "Endro"; }
        if i == 103 { return "Firman"; }
        if i == 104 { return "Irwan"; }
        if i == 105 { return "Ketut"; }
        if i == 106 { return "Ngoc"; }
        if i == 107 { return "Thanh"; }
        if i == 108 { return "Virote"; }
        if i == 109 { return "Wayan"; }
        if i == 110 { return "Yusof"; }
        if i == 111 { return "Zulkifli"; }
        if i == 112 { return "Anh"; }
        if i == 113 { return "Chanthara"; }
        if i == 114 { return "Eka"; }
        if i == 115 { return "Faisal"; }
        if i == 116 { return "Gunawan"; }
        if i == 117 { return "Lam"; }
        if i == 118 { return "Phuc"; }
        if i == 119 { return "San"; }
        if i == 120 { return "Utomo"; }
        if i == 121 { return "Wira"; }
        if i == 122 { return "Sovann"; }
        if i == 123 { return "Thura"; }
        if i == 124 { return "Uthai"; }
        if i == 125 { return "Veasna"; }
        if i == 126 { return "Winai"; }
        if i == 127 { return "Yothin"; }
        if i == 128 { return "Zeya"; }
        if i == 129 { return "Adisak"; }
        if i == 130 { return "Boonmee"; }
        if i == 131 { return "Chaiya"; }
        if i == 132 { return "Dararith"; }
        if i == 133 { return "Ekachai"; }
        if i == 134 { return "Kittisak"; }
        if i == 135 { return "Loem"; }
        if i == 136 { return "Montri"; }
        if i == 137 { return "Oudom"; }
        if i == 138 { return "Piseth"; }
        if i == 139 { return "Rithy"; }
        if i == 140 { return "Sokha"; }
        if i == 141 { return "Thawin"; }
        if i == 142 { return "Vibol"; }
        if i == 143 { return "Wattana"; }
        if i == 144 { return "Yannick-Tho"; }
        if i == 145 { return "Zaw-Min"; }
        if i == 146 { return "Anong"; }
        if i == 147 { return "Borey"; }
        return "Minh";
    }

    public static func GetFemaleFirstName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Linh"; }
        if i == 1 { return "Mai"; }
        if i == 2 { return "Lan"; }
        if i == 3 { return "Huong"; }
        if i == 4 { return "Thanh"; }
        if i == 5 { return "Thi"; }
        if i == 6 { return "Ha"; }
        if i == 7 { return "Thu"; }
        if i == 8 { return "Hoa"; }
        if i == 9 { return "Ngoc"; }
        if i == 10 { return "An"; }
        if i == 11 { return "Binh"; }
        if i == 12 { return "Chi"; }
        if i == 13 { return "Diem"; }
        if i == 14 { return "Em"; }
        if i == 15 { return "Giang"; }
        if i == 16 { return "Hanh"; }
        if i == 17 { return "Kim"; }
        if i == 18 { return "Le"; }
        if i == 19 { return "My"; }
        if i == 20 { return "Nhi"; }
        if i == 21 { return "Oanh"; }
        if i == 22 { return "Phuong"; }
        if i == 23 { return "Quyen"; }
        if i == 24 { return "Suong"; }
        if i == 25 { return "Tam"; }
        if i == 26 { return "Uyen"; }
        if i == 27 { return "Van"; }
        if i == 28 { return "Xuan"; }
        if i == 29 { return "Yen"; }
        if i == 30 { return "Dao"; }
        if i == 31 { return "Fah"; }
        if i == 32 { return "Kanya"; }
        if i == 33 { return "Malai"; }
        if i == 34 { return "Nok"; }
        if i == 35 { return "Orathai"; }
        if i == 36 { return "Pim"; }
        if i == 37 { return "Ratana"; }
        if i == 38 { return "Siri"; }
        if i == 39 { return "Tida"; }
        if i == 40 { return "Waan"; }
        if i == 41 { return "Yim"; }
        if i == 42 { return "Ayu"; }
        if i == 43 { return "Bunga"; }
        if i == 44 { return "Citra"; }
        if i == 45 { return "Dewi"; }
        if i == 46 { return "Eka"; }
        if i == 47 { return "Fitri"; }
        if i == 48 { return "Gita"; }
        if i == 49 { return "Hesti"; }
        if i == 50 { return "Indah"; }
        if i == 51 { return "Juwita"; }
        if i == 52 { return "Kartika"; }
        if i == 53 { return "Lestari"; }
        if i == 54 { return "Maya"; }
        if i == 55 { return "Nur"; }
        if i == 56 { return "Putri"; }
        if i == 57 { return "Ratih"; }
        if i == 58 { return "Sari"; }
        if i == 59 { return "Tika"; }
        if i == 60 { return "Utami"; }
        if i == 61 { return "Wati"; }
        if i == 62 { return "Yanti"; }
        if i == 63 { return "Zara"; }
        if i == 64 { return "Adi"; }
        if i == 65 { return "Bella"; }
        if i == 66 { return "Cahaya"; }
        if i == 67 { return "Dian"; }
        if i == 68 { return "Evi"; }
        if i == 69 { return "Farah"; }
        if i == 70 { return "Gina"; }
        if i == 71 { return "Hana"; }
        if i == 72 { return "Intan"; }
        if i == 73 { return "Jasmine"; }
        if i == 74 { return "Kirana"; }
        if i == 75 { return "Laras"; }
        if i == 76 { return "Melati"; }
        if i == 77 { return "Nina"; }
        if i == 78 { return "Oka"; }
        if i == 79 { return "Puspa"; }
        if i == 80 { return "Rani"; }
        if i == 81 { return "Sinta"; }
        if i == 82 { return "Tari"; }
        if i == 83 { return "Umi"; }
        if i == 84 { return "Vera"; }
        if i == 85 { return "Wulan"; }
        if i == 86 { return "Yuni"; }
        if i == 87 { return "Zahra"; }
        if i == 88 { return "Anita"; }
        if i == 89 { return "Bintang"; }
        if i == 90 { return "Clara"; }
        if i == 91 { return "Diana"; }
        if i == 92 { return "Endah"; }
        if i == 93 { return "Fanny"; }
        if i == 94 { return "Grace"; }
        if i == 95 { return "Helen"; }
        if i == 96 { return "Irma"; }
        if i == 97 { return "Julia"; }
        if i == 98 { return "Kiki"; }
        if i == 99 { return "Lina"; }
        if i == 100 { return "Anh"; }
        if i == 101 { return "Bich"; }
        if i == 102 { return "Chau"; }
        if i == 103 { return "Dara"; }
        if i == 104 { return "Jasmin"; }
        if i == 105 { return "Ngan"; }
        if i == 106 { return "Ratna"; }
        if i == 107 { return "Siti"; }
        if i == 108 { return "Thuy"; }
        if i == 109 { return "Vy"; }
        if i == 110 { return "Zahara"; }
        if i == 111 { return "Aisyah"; }
        if i == 112 { return "Bopha"; }
        if i == 113 { return "Chanthou"; }
        if i == 114 { return "Farida"; }
        if i == 115 { return "Hang"; }
        if i == 116 { return "Kim-Ly"; }
        if i == 117 { return "Nhung"; }
        if i == 118 { return "Puspita"; }
        if i == 119 { return "Rina"; }
        if i == 120 { return "Sopheap"; }
        if i == 121 { return "Trang"; }
        if i == 122 { return "Utari"; }
        if i == 123 { return "Vania"; }
        if i == 124 { return "Champa"; }
        if i == 125 { return "Duyen"; }
        if i == 126 { return "Sokhem"; }
        if i == 127 { return "Thida"; }
        if i == 128 { return "Utharat"; }
        if i == 129 { return "Veata"; }
        if i == 130 { return "Wipha"; }
        if i == 131 { return "Yani"; }
        if i == 132 { return "Zeyar"; }
        if i == 133 { return "Achara"; }
        if i == 134 { return "Bopha-Devi"; }
        if i == 135 { return "Chenda"; }
        if i == 136 { return "Davi"; }
        if i == 137 { return "Ekarin"; }
        if i == 138 { return "Hansa"; }
        if i == 139 { return "Kanda"; }
        if i == 140 { return "Leakena"; }
        if i == 141 { return "Malis"; }
        if i == 142 { return "Nary"; }
        if i == 143 { return "Pisey"; }
        if i == 144 { return "Ratanak"; }
        if i == 145 { return "Sokhany"; }
        if i == 146 { return "Theary"; }
        if i == 147 { return "Vanna"; }
        if i == 148 { return "Wassana"; }
        if i == 149 { return "Yaowaluk"; }
        return "Linh";
    }

    public static func GetLastName(seed: Int32) -> String {
        let i = RandRange(seed, 0, 150);
        if i == 0 { return "Nguyen"; }
        if i == 1 { return "Tran"; }
        if i == 2 { return "Pham"; }
        if i == 3 { return "Vu"; }
        if i == 4 { return "Dang"; }
        if i == 5 { return "Bui"; }
        if i == 6 { return "Do"; }
        if i == 7 { return "Ho"; }
        if i == 8 { return "Ngo"; }
        if i == 9 { return "Le"; }
        if i == 10 { return "Hoang"; }
        if i == 11 { return "Huynh"; }
        if i == 12 { return "Vo"; }
        if i == 13 { return "Phan"; }
        if i == 14 { return "Truong"; }
        if i == 15 { return "Duong"; }
        if i == 16 { return "Ly"; }
        if i == 17 { return "Ton"; }
        if i == 18 { return "Tang"; }
        if i == 19 { return "Lam"; }
        if i == 20 { return "Chanthavong"; }
        if i == 21 { return "Boupha"; }
        if i == 22 { return "Khamvongsa"; }
        if i == 23 { return "Phongsavanh"; }
        if i == 24 { return "Sihavong"; }
        if i == 25 { return "Srisombath"; }
        if i == 26 { return "Thammavong"; }
        if i == 27 { return "Vongphoumy"; }
        if i == 28 { return "Chanthala"; }
        if i == 29 { return "Keosavang"; }
        if i == 30 { return "Charoensuk"; }
        if i == 31 { return "Sukhumvit"; }
        if i == 32 { return "Pongsakul"; }
        if i == 33 { return "Rattanakorn"; }
        if i == 34 { return "Siriwan"; }
        if i == 35 { return "Tangtrongchit"; }
        if i == 36 { return "Wongsawat"; }
        if i == 37 { return "Yingyong"; }
        if i == 38 { return "Boonlert"; }
        if i == 39 { return "Chaiyasit"; }
        if i == 40 { return "Suryono"; }
        if i == 41 { return "Wijaya"; }
        if i == 42 { return "Kusuma"; }
        if i == 43 { return "Hartono"; }
        if i == 44 { return "Santoso"; }
        if i == 45 { return "Sutanto"; }
        if i == 46 { return "Hidayat"; }
        if i == 47 { return "Pratama"; }
        if i == 48 { return "Putra"; }
        if i == 49 { return "Sanjaya"; }
        if i == 50 { return "Abdullah"; }
        if i == 51 { return "Bakri"; }
        if i == 52 { return "Chong"; }
        if i == 53 { return "Darmawan"; }
        if i == 54 { return "Effendi"; }
        if i == 55 { return "Firmansyah"; }
        if i == 56 { return "Gunawan"; }
        if i == 57 { return "Halim"; }
        if i == 58 { return "Ibrahim"; }
        if i == 59 { return "Jatmiko"; }
        if i == 60 { return "Kartawijaya"; }
        if i == 61 { return "Lim"; }
        if i == 62 { return "Mahendra"; }
        if i == 63 { return "Nugraha"; }
        if i == 64 { return "Oei"; }
        if i == 65 { return "Pranoto"; }
        if i == 66 { return "Qureshi"; }
        if i == 67 { return "Rachman"; }
        if i == 68 { return "Setiawan"; }
        if i == 69 { return "Tan"; }
        if i == 70 { return "Utomo"; }
        if i == 71 { return "Vong"; }
        if i == 72 { return "Wibowo"; }
        if i == 73 { return "Xaysana"; }
        if i == 74 { return "Yusof"; }
        if i == 75 { return "Zainal"; }
        if i == 76 { return "Aguilar"; }
        if i == 77 { return "Bautista"; }
        if i == 78 { return "Cruz"; }
        if i == 79 { return "Dela Cruz"; }
        if i == 80 { return "Espiritu"; }
        if i == 81 { return "Fernandez"; }
        if i == 82 { return "Garcia"; }
        if i == 83 { return "Hernandez"; }
        if i == 84 { return "Ilagan"; }
        if i == 85 { return "Jimenez"; }
        if i == 86 { return "Koh"; }
        if i == 87 { return "Lopez"; }
        if i == 88 { return "Mendoza"; }
        if i == 89 { return "Ng"; }
        if i == 90 { return "Ong"; }
        if i == 91 { return "Pascual"; }
        if i == 92 { return "Quizon"; }
        if i == 93 { return "Reyes"; }
        if i == 94 { return "Santos"; }
        if i == 95 { return "Tiu"; }
        if i == 96 { return "Uy"; }
        if i == 97 { return "Villanueva"; }
        if i == 98 { return "Wong"; }
        if i == 99 { return "Yap"; }
        if i == 100 { return "Aquino"; }
        if i == 101 { return "Chea"; }
        if i == 102 { return "Eng"; }
        if i == 103 { return "Iskandar"; }
        if i == 104 { return "Jaafar"; }
        if i == 105 { return "Khoo"; }
        if i == 106 { return "Mahmud"; }
        if i == 107 { return "Ocampo"; }
        if i == 108 { return "Quach"; }
        if i == 109 { return "Trinh"; }
        if i == 110 { return "Ung"; }
        if i == 111 { return "Bacani"; }
        if i == 112 { return "Cheam"; }
        if i == 113 { return "Dinh"; }
        if i == 114 { return "Escobar"; }
        if i == 115 { return "Fajardo"; }
        if i == 116 { return "Goh"; }
        if i == 117 { return "Hashim"; }
        if i == 118 { return "Ismail"; }
        if i == 119 { return "Javier"; }
        if i == 120 { return "Keo"; }
        if i == 121 { return "Luong"; }
        if i == 122 { return "Nop"; }
        if i == 123 { return "Ramos"; }
        if i == 124 { return "Salim"; }
        if i == 125 { return "Tolentino"; }
        if i == 126 { return "Utama"; }
        if i == 127 { return "Widodo"; }
        if i == 128 { return "Yusuf"; }
        if i == 129 { return "Zamora"; }
        if i == 130 { return "Chandra"; }
        if i == 131 { return "Sok"; }
        if i == 132 { return "Thach"; }
        if i == 133 { return "Uch"; }
        if i == 134 { return "Vann"; }
        if i == 135 { return "Wong-Sar"; }
        if i == 136 { return "Yim"; }
        if i == 137 { return "Zaw-Htet"; }
        if i == 138 { return "Ang"; }
        if i == 139 { return "Bou"; }
        if i == 140 { return "Chhim"; }
        if i == 141 { return "Ek"; }
        if i == 142 { return "Heng-Ly"; }
        if i == 143 { return "Kim-Seng"; }
        if i == 144 { return "Mao"; }
        if i == 145 { return "Nhem"; }
        if i == 146 { return "Ouk"; }
        if i == 147 { return "Pen"; }
        if i == 148 { return "Rath"; }
        if i == 149 { return "Sam"; }
        return "Nguyen";
    }
}
