// Kiroshi Deep Scan Protocol - French Language Package (PARTIAL / TEST)
// Covers UI section headers, all scanner loading lines, and all BOLO
// notices — 255 of 11,329 keys. Untranslated keys fall back to English.
// Serves as the live example of the v3 translation workflow.

module KiroshiDeepScan.Localization
import Codeware.Localization.*

public class French extends ModLocalizationPackage {
    protected func DefineTexts() -> Void {
        this.DefineTexts0();
        this.DefineTexts1();
    }

    private func DefineTexts0() -> Void {
        this.Text("Kdsp-Bolo-0", "BOLO : Personne d'intérêt — enquête pour homicide à Watson");
        this.Text("Kdsp-Bolo-1", "BOLO : Personne d'intérêt — réseau de vol organisé en magasin");
        this.Text("Kdsp-Bolo-10", "BOLO : Le sujet pourrait détenir des images d'une affaire en cours");
        this.Text("Kdsp-Bolo-11", "BOLO : Dernier témoin confirmé d'une victime d'homicide — entretien en attente");
        this.Text("Kdsp-Bolo-12", "BOLO : Cité dans une déposition — déclaration jamais recueillie");
        this.Text("Kdsp-Bolo-13", "AVIS : Témoin protégé [DÉTAILS SCELLÉS — NE PAS APPROCHER]");
        this.Text("Kdsp-Bolo-14", "ALERTE : Correspondance faciale à 87% — avis de disparition #NC-");
        this.Text("Kdsp-Bolo-15", "ALERTE : Le sujet correspond au signalement — disparition déclarée par la famille");
        this.Text("Kdsp-Bolo-16", "ALERTE : Porté disparu par son employeur en ");
        this.Text("Kdsp-Bolo-17", "ALERTE : Déclaré légalement mort en ");
        this.Text("Kdsp-Bolo-18", "ALERTE : Correspondance partielle — inconnu(e) repêché(e) dans la baie de Del Coronado [SURVIVANT]");
        this.Text("Kdsp-Bolo-19", "ALERTE : Le sujet correspond à l'image vieillie — enfant disparu depuis ");
        this.Text("Kdsp-Bolo-2", "BOLO : Personne d'intérêt — incendie criminel, entrepôt de Northside");
        this.Text("Kdsp-Bolo-20", "AVIS : Récupération d'actifs corpo — matériel d'entreprise non restitué");
        this.Text("Kdsp-Bolo-21", "AVIS : L'ancien employeur demande des données de localisation [LITIGE CONTRACTUEL]");
        this.Text("Kdsp-Bolo-22", "AVIS : Surveillance d'application de NDA — veille juridique corpo active");
        this.Text("Kdsp-Bolo-23", "AVIS : Demande de localisation d'une agence de recouvrement au dossier");
        this.Text("Kdsp-Bolo-24", "AVIS : Réclamation pour violation de non-concurrence — suivi juridique corpo");
        this.Text("Kdsp-Bolo-25", "AVIS : Procédure de récupération d'indemnités — localisation demandée par le service juridique Arasaka");
        this.Text("Kdsp-Bolo-26", "AVIS : Absence à l'entretien de départ Militech — révocation d'habilitation incomplète");
        this.Text("Kdsp-Bolo-27", "AVIS : Exécution d'expulsion de logement corpo — logement jamais libéré");
        this.Text("Kdsp-Bolo-28", "ALERTE : Le sujet conserve un accès biométrique actif à un site fermé");
        this.Text("Kdsp-Bolo-29", "BOLO : Contrôle de bien-être demandé par la famille — introuvable");
        this.Text("Kdsp-Bolo-3", "BOLO : Recherché pour interrogatoire — affaire de trafic de braindances");
        this.Text("Kdsp-Bolo-30", "AVIS : Convocation de juré — trois tentatives de remise échouées");
        this.Text("Kdsp-Bolo-31", "AVIS : Assignation en attente de signification — affaire civile");
        this.Text("Kdsp-Bolo-32", "AVIS : Statut d'immigration en révision — date d'audience dépassée");
        this.Text("Kdsp-Bolo-33", "AVIS : Héritage non réclamé — le tribunal des successions recherche l'héritier");
        this.Text("Kdsp-Bolo-34", "AVIS : Non-réponse au recensement — visites de l'agent refusées");
        this.Text("Kdsp-Bolo-35", "AVIS : Demande de localisation pour pension alimentaire");
        this.Text("Kdsp-Bolo-36", "AVIS : Jugement locatif — adresse de paiement inconnue");
        this.Text("Kdsp-Bolo-37", "AVIS : Restitution de véhicule en fourrière — propriétaire injoignable");
        this.Text("Kdsp-Bolo-38", "ALERTE : Rappel de cyberware — lot d'implants signalé défectueux");
        this.Text("Kdsp-Bolo-39", "ALERTE : Suivi d'essai clinique en retard — demande de surveillance Biotechnica");
        this.Text("Kdsp-Bolo-4", "BOLO : Recherché pour interrogatoire — enquête sur un atelier clandestin de cyberware");
        this.Text("Kdsp-Bolo-40", "ALERTE : Cité comme contact d'urgence dans une enquête de décès ouverte");
        this.Text("Kdsp-Bolo-41", "ALERTE : Rappel de donneur de sang — groupe rare requis, coordonnées obsolètes");
        this.Text("Kdsp-Bolo-42", "ALERTE : Notification d'exposition — incident industriel, ");
        this.Text("Kdsp-Bolo-43", "ALERTE : Compatibilité de greffe d'organe — Trauma Team n'a pas pu joindre");
        this.Text("Kdsp-Bolo-44", "ALERTE : Suivi post-hospitalisation psychiatrique — deux évaluations manquées");
        this.Text("Kdsp-Bolo-45", "AVIS : Règlement pour faute d'un charcudoc — localisation du plaignant requise");
        this.Text("Kdsp-Bolo-46", "AVIS : Signalement NetWatch — l'alias du sujet apparaît dans des journaux de serveurs saisis");
        this.Text("Kdsp-Bolo-47", "AVIS : Anomalie de flux de données tracée jusqu'au deck du sujet");
        this.Text("Kdsp-Bolo-48", "ALERTE : SIN du sujet cloné — douze utilisateurs simultanés détectés");
        this.Text("Kdsp-Bolo-49", "AVIS : Acheteur signalé de logiciels de percée d'ICE réglementés");
        this.Text("Kdsp-Bolo-5", "BOLO : Personne d'intérêt — réseau de contrebande, baie de Del Coronado");
        this.Text("Kdsp-Bolo-50", "ALERTE : Victime de vol d'identité — dossier #NC-");
        this.Text("Kdsp-Bolo-51", "BOLO : Cible signalée d'une menace active de représailles de gang");
        this.Text("Kdsp-Bolo-52", "AVIS : Le sujet figure sur la liste de clients saisie d'un fixer — portée inconnue");
        this.Text("Kdsp-Bolo-53", "AVIS : Nom retrouvé dans le registre de cibles d'une équipe de charognards");
        this.Text("Kdsp-Bolo-54", "BOLO : Victime possible d'extorsion — schéma correspondant à un racket de protection");
        this.Text("Kdsp-Bolo-55", "AVIS : Fréquente un établissement sous surveillance active du NCPD");
        this.Text("Kdsp-Bolo-56", "AVIS : Compte gelé en attente d'examen pour fraude — titulaire injoignable");
        this.Text("Kdsp-Bolo-57", "AVIS : Bénéficiaire désigné d'une indemnité d'assurance non réclamée");
        this.Text("Kdsp-Bolo-58", "AVIS : Coffre-fort en impayé — contenu programmé pour vente aux enchères");
        this.Text("Kdsp-Bolo-59", "ALERTE : Schéma de fractionnement signalé — transactions juste sous le seuil de déclaration");
        this.Text("Kdsp-Bolo-6", "BOLO : Recherché pour interrogatoire — distribution de médicaments contrefaits");
        this.Text("Kdsp-Bolo-60", "AVIS : Défaut de co-signataire — le prêteur poursuit le débiteur secondaire");
        this.Text("Kdsp-Bolo-61", "ALERTE : Contrat de localisation privé au dossier — identité du client protégée");
        this.Text("Kdsp-Bolo-62", "AVIS : Déchéance de caution — agent de recouvrement autorisé");
        this.Text("Kdsp-Bolo-63", "AVIS : Recherche de fugitif active — trois agences détiennent le même contrat");
        this.Text("Kdsp-Bolo-64", "ALERTE : Sujet listé dans une base de cibles mercenaires divulguée [NON VÉRIFIÉ]");
        this.Text("Kdsp-Bolo-65", "AVIS : Révision ADN d'affaire classée — profil du sujet demandé pour élimination");
        this.Text("Kdsp-Bolo-66", "AVIS : Cité dans un rapport d'incident de ");
        this.Text("Kdsp-Bolo-67", "AVIS : Incohérence des registres d'avant l'unification — vérification d'identité demandée");
        this.Text("Kdsp-Bolo-68", "AVIS : Sujet de trois signalements anonymes distincts — tous non vérifiés");
        this.Text("Kdsp-Bolo-69", "BOLO : Véhicule immatriculé au nom du sujet vu quittant une scène de crime [NON CONFIRMÉ]");
        this.Text("Kdsp-Bolo-7", "BOLO : Personne d'intérêt — série de cambriolages en mégabâtiment");
        this.Text("Kdsp-Bolo-70", "AVIS : Apparitions répétées dans des dossiers sans lien — anomalie statistique signalée");
        this.Text("Kdsp-Bolo-71", "ALERTE : Signature biométrique en double enregistrée dans un autre district [IMPOSSIBLE]");
        this.Text("Kdsp-Bolo-16b", " — dossier jamais clos");
        this.Text("Kdsp-Bolo-17b", " — la biométrie dit le contraire");
        this.Text("Kdsp-Bolo-50b", " — entretien de vérification en attente");
        this.Text("Kdsp-Bolo-66b", " — affaire rouverte");
        this.Text("Kdsp-Bolo-8", "BOLO : Témoin clé — fusillade de gang, n'a pas répondu à la convocation");
        this.Text("Kdsp-Bolo-9", "BOLO : Candidat à la relocalisation de témoin — contacter le NCPD avant approche");
        this.Text("Kdsp-LoadConnection-0", "Initialisation du protocole Kiroshi Deep Scan...");
        this.Text("Kdsp-LoadConnection-1", "Établissement d'un contournement NetWatch sécurisé...");
        this.Text("Kdsp-LoadConnection-10", "Verrouillage du schéma neural acquis...");
        this.Text("Kdsp-LoadConnection-11", "Ping des nœuds de la dataforteresse de Night City...");
        this.Text("Kdsp-LoadConnection-12", "Poignée de main quantique initiée...");
        this.Text("Kdsp-LoadConnection-13", "Synchronisation de l'implant optique terminée...");
        this.Text("Kdsp-LoadConnection-14", "Sous-systèmes Kiroshi en ligne...");
        this.Text("Kdsp-LoadConnection-2", "Falsification des identifiants d'authentification...");
        this.Text("Kdsp-LoadConnection-3", "Liaison neurale Kiroshi Mk.IV établie...");
        this.Text("Kdsp-LoadConnection-4", "Routage de la connexion via un nœud proxy...");
        this.Text("Kdsp-LoadConnection-5", "Connexion au serveur central du NCPD...");
        this.Text("Kdsp-LoadConnection-6", "Lancement du scan biométrique multi-spectre...");
        this.Text("Kdsp-LoadConnection-7", "Sous-programme Deep Scan chargé...");
        this.Text("Kdsp-LoadConnection-8", "Activation du mode de reconnaissance passive...");
        this.Text("Kdsp-LoadConnection-9", "Calibration de la matrice de reconnaissance optique...");
        this.Text("Kdsp-LoadDatabase-0", "Accès à la base criminelle du NCPD...");
        this.Text("Kdsp-LoadDatabase-1", "Interrogation du registre médical de Night City...");
        this.Text("Kdsp-LoadDatabase-10", "Extraction des vérifications d'emploi...");
        this.Text("Kdsp-LoadDatabase-11", "Accès aux dossiers judiciaires scellés...");
        this.Text("Kdsp-LoadDatabase-12", "Récupération des données de reconnaissance faciale du NCPD...");
        this.Text("Kdsp-LoadDatabase-13", "Interrogation de la base des employés Zetatech...");
        this.Text("Kdsp-LoadDatabase-14", "Analyse du registre des essais médicaux Biotechnica...");
        this.Text("Kdsp-LoadDatabase-15", "Accès aux manifestes d'import/export Kang Tao...");
        this.Text("Kdsp-LoadDatabase-16", "Extraction des communications signalées par NetWatch...");
        this.Text("Kdsp-LoadDatabase-17", "Interrogation de la base des sous-traitants Petrochem...");
        this.Text("Kdsp-LoadDatabase-18", "Accès aux registres fiscaux de Night City...");
        this.Text("Kdsp-LoadDatabase-19", "Extraction des rapports d'intervention Trauma Team...");
        this.Text("Kdsp-LoadDatabase-2", "Extraction des enregistrements de cyberware...");
        this.Text("Kdsp-LoadDatabase-3", "Analyse de la base de couverture Trauma Team...");
        this.Text("Kdsp-LoadDatabase-4", "Accès au nœud bancaire Arasaka [CHIFFRÉ]...");
        this.Text("Kdsp-LoadDatabase-5", "Récupération des dossiers d'immigration...");
        this.Text("Kdsp-LoadDatabase-6", "Déchiffrement des dossiers du personnel Militech...");
        this.Text("Kdsp-LoadDatabase-7", "Connexion au réseau des charcudocs...");
        this.Text("Kdsp-LoadDatabase-8", "Accès à la base de crédit social...");
        this.Text("Kdsp-LoadDatabase-9", "Interrogation du registre des affiliations de gangs...");
        this.Text("Kdsp-LoadDistrict-0", "Accès au nœud des registres municipaux de Watson...");
        this.Text("Kdsp-LoadDistrict-1", "Routage via le réseau maillé du marché de Kabuki...");
        this.Text("Kdsp-LoadDistrict-10", "Contournement des moniteurs de trafic des Tyger Claws...");
        this.Text("Kdsp-LoadDistrict-11", "Détournement d'une liaison d'un salon BD de Japantown...");
        this.Text("Kdsp-LoadDistrict-12", "Négociation de la couche de chiffrement corpo...");
        this.Text("Kdsp-LoadDistrict-13", "Contournement de la zone d'exclusion de la tour Arasaka...");
        this.Text("Kdsp-LoadDistrict-14", "Accès au nœud du quartier financier de City Center...");
        this.Text("Kdsp-LoadDistrict-15", "Falsification des identifiants de la place corporative...");
        this.Text("Kdsp-LoadDistrict-16", "Évasion des renifleurs de périmètre Militech...");
        this.Text("Kdsp-LoadDistrict-17", "Interrogation du réseau de surveillance du centre-ville...");
        this.Text("Kdsp-LoadDistrict-18", "Routage via le réseau maillé du barrio de Heywood...");
        this.Text("Kdsp-LoadDistrict-19", "Interrogation du nœud communautaire de Vista del Rey...");
        this.Text("Kdsp-LoadDistrict-2", "Interrogation du registre du district de Little China...");
        this.Text("Kdsp-LoadDistrict-20", "Accès à la sous-station municipale de The Glen...");
        this.Text("Kdsp-LoadDistrict-21", "Évitement des canaux surveillés par les Valentinos...");
        this.Text("Kdsp-LoadDistrict-22", "Interception de la dorsale de transit de Wellsprings...");
        this.Text("Kdsp-LoadDistrict-23", "Connexion à un relais de bodega de Heywood...");
        this.Text("Kdsp-LoadDistrict-24", "Routage via la ligne industrielle d'Arroyo...");
        this.Text("Kdsp-LoadDistrict-25", "Accès au réseau des usines de Santo Domingo...");
        this.Text("Kdsp-LoadDistrict-26", "Interrogation du registre du logement de Rancho Coronado...");
        this.Text("Kdsp-LoadDistrict-27", "Interception d'un canal de maintenance de la centrale...");
        this.Text("Kdsp-LoadDistrict-28", "Contournement des scanners de checkpoint du 6th Street...");
        this.Text("Kdsp-LoadDistrict-29", "Négociation avec un serveur syndical d'Arroyo...");
        this.Text("Kdsp-LoadDistrict-3", "Ping du sous-réseau industriel de Northside...");
        this.Text("Kdsp-LoadDistrict-30", "Routage via un relais darknet de Pacifica...");
        this.Text("Kdsp-LoadDistrict-31", "Récupération de bande passante sur l'infrastructure morte du resort...");
        this.Text("Kdsp-LoadDistrict-32", "Évitement du territoire netrunner des Voodoo Boys...");
        this.Text("Kdsp-LoadDistrict-33", "Interrogation du dernier nœud fonctionnel de Coastview...");
        this.Text("Kdsp-LoadDistrict-34", "ATTENTION : Aucune couverture municipale — passage par le darknet...");
        this.Text("Kdsp-LoadDistrict-35", "Percée de la liste noire NetWatch de Pacifica...");
        this.Text("Kdsp-LoadDistrict-36", "Percée sous le brouillage de Barghest...");
        this.Text("Kdsp-LoadDistrict-37", "Routage via les fréquences des contrebandiers...");
        this.Text("Kdsp-LoadDistrict-38", "ATTENTION : Dogtown — aucune donnée NCPD disponible...");
        this.Text("Kdsp-LoadDistrict-39", "Négociation avec un courtier en données du marché noir...");
        this.Text("Kdsp-LoadDistrict-4", "Interception du flux du commissariat NCPD de Watson...");
        this.Text("Kdsp-LoadDistrict-40", "Détournement d'une liaison de patrouille Barghest [RISQUÉ]...");
        this.Text("Kdsp-LoadDistrict-41", "Accès aux archives municipales d'avant le blocus...");
        this.Text("Kdsp-LoadDistrict-42", "Amplification du signal — relais le plus proche à 12 km...");
        this.Text("Kdsp-LoadDistrict-43", "Routage via un répéteur de convoi nomade...");
        this.Text("Kdsp-LoadDistrict-44", "Interrogation de la maigre couverture satellite des Badlands...");
        this.Text("Kdsp-LoadDistrict-45", "ATTENTION : Les registres ruraux peuvent dater de plusieurs années...");
        this.Text("Kdsp-LoadDistrict-46", "Interception d'une station Petrochem abandonnée...");
        this.Text("Kdsp-LoadDistrict-47", "Connexion au réseau maillé des routiers longue distance...");
        this.Text("Kdsp-LoadDistrict-48", "Triangulation des nœuds d'infrastructure locaux...");
        this.Text("Kdsp-LoadDistrict-49", "Routage via le relais municipal le plus proche...");
        this.Text("Kdsp-LoadDistrict-5", "Négociation avec un nœud local piraté par les Tyger Claws...");
        this.Text("Kdsp-LoadDistrict-50", "Interrogation des services de registre du district...");
        this.Text("Kdsp-LoadDistrict-6", "Routage via le réseau commercial de Japantown...");
        this.Text("Kdsp-LoadDistrict-7", "Accès au registre des résidents de Charter Hill [CHIFFRÉ]...");
        this.Text("Kdsp-LoadDistrict-8", "Interrogation des journaux de sécurité privée de North Oak...");
        this.Text("Kdsp-LoadDistrict-9", "Connexion au réseau des boutiques de luxe de Westbrook...");
        this.Text("Kdsp-LoadError-0", "ATTENTION : Dossiers partiels détectés");
        this.Text("Kdsp-LoadError-1", "ERREUR : Délai du nœud Arasaka... nouvelle tentative...");
        this.Text("Kdsp-LoadError-10", "ERREUR : Pare-feu Militech... percée en cours...");
        this.Text("Kdsp-LoadError-11", "ATTENTION : Bloc de données corrompu... reconstruction...");
        this.Text("Kdsp-LoadError-12", "ALERTE : Tentative de traçage détectée... masquage...");
        this.Text("Kdsp-LoadError-13", "ERREUR : Délai du nœud NCPD... basculement...");
        this.Text("Kdsp-LoadError-14", "ATTENTION : Casier judiciaire [EFFACÉ - RÉCUPÉRATION]");
        this.Text("Kdsp-LoadError-15", "AVIS : Certains dossiers peuvent être obsolètes");
        this.Text("Kdsp-LoadError-16", "ERREUR : Serveur Kang Tao injoignable... ignoré...");
        this.Text("Kdsp-LoadError-17", "ATTENTION : Données d'immigration incomplètes");
        this.Text("Kdsp-LoadError-18", "ALERTE : Signature Black ICE... neutralisation...");
        this.Text("Kdsp-LoadError-19", "ERREUR : Connexion Zetatech perdue... nouvelle tentative...");
        this.Text("Kdsp-LoadError-2", "ALERTE : Sonde NetWatch détectée... évasion...");
        this.Text("Kdsp-LoadError-20", "ATTENTION : Le sujet porte un implant de contre-surveillance");
        this.Text("Kdsp-LoadError-21", "AVIS : Archives uniquement - aucune donnée en direct");
        this.Text("Kdsp-LoadError-22", "ERREUR : Déchiffrement échoué... clé de secours...");
        this.Text("Kdsp-LoadError-23", "ATTENTION : Contrôle d'intégrité échoué... vérification...");
        this.Text("Kdsp-LoadError-3", "Connexion interrompue... reconnexion...");
        this.Text("Kdsp-LoadError-4", "ERREUR : Requête échouée... reroutage...");
        this.Text("Kdsp-LoadError-5", "ATTENTION : Données financières incomplètes");
        this.Text("Kdsp-LoadError-6", "ALERTE : ICE corporatif détecté... contournement...");
        this.Text("Kdsp-LoadError-7", "ERREUR : Authentification rejetée... falsification...");
        this.Text("Kdsp-LoadError-8", "ATTENTION : Dossiers médicaux [PARTIELLEMENT SCELLÉS]");
        this.Text("Kdsp-LoadError-9", "AVIS : Sujet signalé dans 2 bases de données");
        this.Text("Kdsp-LoadProcessing-0", "Compilation de la matrice d'évaluation des menaces...");
        this.Text("Kdsp-LoadProcessing-1", "Analyse des signatures neurales...");
        this.Text("Kdsp-LoadProcessing-10", "Analyse du modèle de prédiction comportementale...");
        this.Text("Kdsp-LoadProcessing-11", "Traitement des grappes de données biométriques...");
        this.Text("Kdsp-LoadProcessing-12", "Exécution du sous-programme de reconnaissance faciale...");
        this.Text("Kdsp-LoadProcessing-13", "Décodage des dossiers médicaux chiffrés...");
        this.Text("Kdsp-LoadProcessing-14", "Triangulation des dernières positions connues...");
        this.Text("Kdsp-LoadProcessing-15", "Analyse des connexions du réseau social...");
        this.Text("Kdsp-LoadProcessing-16", "Évaluation des marqueurs psychologiques...");
        this.Text("Kdsp-LoadProcessing-17", "Recoupement des déclarations de témoins...");
        this.Text("Kdsp-LoadProcessing-18", "Analyse des habitudes de dépenses...");
        this.Text("Kdsp-LoadProcessing-19", "Reconstruction de l'historique des déplacements...");
        this.Text("Kdsp-LoadProcessing-2", "Traitement des fragments de casier judiciaire...");
        this.Text("Kdsp-LoadProcessing-3", "Exécution de l'algorithme de vérification...");
        this.Text("Kdsp-LoadProcessing-4", "Corrélation des associés connus...");
        this.Text("Kdsp-LoadProcessing-5", "Cartographie de l'historique des transactions...");
        this.Text("Kdsp-LoadProcessing-6", "Reconstruction du parcours professionnel...");
        this.Text("Kdsp-LoadProcessing-7", "Vérification des numéros de série du cyberware...");
    }

    private func DefineTexts1() -> Void {
        this.Text("Kdsp-LoadProcessing-8", "Calcul de l'indice de risque de cyberpsychose...");
        this.Text("Kdsp-LoadProcessing-9", "Recoupement avec la base des tatouages de gangs...");
        this.Text("Kdsp-LoadStatus-0", "Contournement du pare-feu Militech... RÉUSSI");
        this.Text("Kdsp-LoadStatus-1", "Évasion des contre-mesures Arasaka...");
        this.Text("Kdsp-LoadStatus-10", "Évaluation de menace en temps réel : MINIMALE");
        this.Text("Kdsp-LoadStatus-11", "Pénétration du pare-feu : 100%");
        this.Text("Kdsp-LoadStatus-12", "Contre-mesures ICE : NEUTRALISÉES");
        this.Text("Kdsp-LoadStatus-13", "Détection de Black ICE : NÉGATIVE");
        this.Text("Kdsp-LoadStatus-14", "Injection de daemon : NON REQUISE");
        this.Text("Kdsp-LoadStatus-15", "Traçage de route : MASQUÉ");
        this.Text("Kdsp-LoadStatus-16", "Surveillance NCPD : ÉVITÉE");
        this.Text("Kdsp-LoadStatus-17", "Supervision corporative : AUCUNE DÉTECTÉE");
        this.Text("Kdsp-LoadStatus-18", "Chaîne de proxys : 7 nœuds actifs");
        this.Text("Kdsp-LoadStatus-19", "Puissance du signal : OPTIMALE");
        this.Text("Kdsp-LoadStatus-2", "Frais de courtier : 0,02 eddies [AUTO-PAYÉ]");
        this.Text("Kdsp-LoadStatus-3", "Connexion stable. Aucune trace détectée.");
        this.Text("Kdsp-LoadStatus-4", "Nettoyage des journaux proxy...");
        this.Text("Kdsp-LoadStatus-5", "Niveau d'alerte NetWatch : VERT");
        this.Text("Kdsp-LoadStatus-6", "Masquage du point d'origine... TERMINÉ");
        this.Text("Kdsp-LoadStatus-7", "Vérification de l'intégrité des données...");
        this.Text("Kdsp-LoadStatus-8", "Sources secondaires : 3 correspondances");
        this.Text("Kdsp-LoadStatus-9", "Recherche d'archives : 847 dossiers analysés");
        this.Text("Kdsp-LoadSuccess-0", "Scan terminé. Affichage des résultats.");
        this.Text("Kdsp-LoadSuccess-1", "Compilation terminée. Fiabilité : 94,7%");
        this.Text("Kdsp-LoadSuccess-10", "Compilation réussie. 12 dossiers fusionnés.");
        this.Text("Kdsp-LoadSuccess-11", "Requête terminée. Évaluation de menace prête.");
        this.Text("Kdsp-LoadSuccess-12", "Profil verrouillé. Affichage des données.");
        this.Text("Kdsp-LoadSuccess-13", "Scan finalisé. Précision : 97,2%");
        this.Text("Kdsp-LoadSuccess-14", "Toutes les bases interrogées. Résultats compilés.");
        this.Text("Kdsp-LoadSuccess-15", "Agrégation des données terminée. Rendu...");
        this.Text("Kdsp-LoadSuccess-16", "Analyse du sujet terminée. Affichage...");
        this.Text("Kdsp-LoadSuccess-17", "Génération du profil réussie.");
        this.Text("Kdsp-LoadSuccess-2", "Profil assemblé depuis 7 sources de données.");
        this.Text("Kdsp-LoadSuccess-3", "Systèmes nominaux. Rendu en cours.");
        this.Text("Kdsp-LoadSuccess-4", "Analyse terminée. Aucune anomalie détectée.");
        this.Text("Kdsp-LoadSuccess-5", "Profil du sujet compilé avec succès.");
        this.Text("Kdsp-LoadSuccess-6", "Requête terminée. Rendu en cours...");
        this.Text("Kdsp-LoadSuccess-7", "Dossiers récupérés. Traitement terminé.");
        this.Text("Kdsp-LoadSuccess-8", "Scan profond terminé. Fiabilité : ÉLEVÉE");
        this.Text("Kdsp-LoadSuccess-9", "Dossier de renseignement prêt. Affichage du profil.");
        this.Text("Kdsp-UI-Background", "Antécédents");
        this.Text("Kdsp-UI-CriminalRecord", "Casier judiciaire");
        this.Text("Kdsp-UI-Cyberware", "Cyberware");
        this.Text("Kdsp-UI-DebugInfo", "Infos de débogage");
        this.Text("Kdsp-UI-EarlyLife", "Jeunesse");
        this.Text("Kdsp-UI-Financial", "Finances");
        this.Text("Kdsp-UI-GangAffiliation", "Affiliation de gang");
        this.Text("Kdsp-UI-Medical", "Dossier médical");
        this.Text("Kdsp-UI-NETProfile", "Profil NET");
        this.Text("Kdsp-UI-NetworkAnalysis", "Analyse réseau");
        this.Text("Kdsp-UI-Pronouns", "Pronoms");
        this.Text("Kdsp-UI-PsychProfile", "Profil psychologique");
        this.Text("Kdsp-UI-RecentActivity", "Activité récente");
        this.Text("Kdsp-UI-Relationships", "Relations");
        this.Text("Kdsp-UI-VehicleRegistration", "Immatriculation");
    }

}
